### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by scrouthtv** [folke/todo-comments.nvim#1]
Hello, 

I just tried using your plugin. This is my entire `init.vim`:
```
call plugin#begin()
Plug 'folke/todo-comments.nvim'
call plug#end()
```
and I tried this file (`test.c`):
```
// PERF
// HACK
// TODO
// NOTE
// FIX
// WARNING
int main() {
	return 0;
}
```
Only the `TODO` gets highlighted, and when I try to run `:TodoQuickFix`, I get
```
Error executing vim.schedule lua callback: .../plugged/todo-comments.nvim/lua/todo-comment
s/search.lua:67: attempt to index field 'fn' (a nil value)
```

Do you have any idea what I'm missing? 

Thanks in advance

**Comment by folke** [comment]
Are you using Neovim nightly? 0.5

**Comment by scrouthtv** [comment]
No, `NVIM v0.4.4`. Do I need nightly?

**Comment by folke** [comment]
Yep, see the [requirements](https://github.com/folke/todo-comments.nvim#%EF%B8%8F-requirements)

**Comment by scrouthtv** [comment]
Oh yeah, sorry
