### ISSUE TITLE
[Feature Request]: highlight author in `TODO(author):`

### ISSUE THREAD

**Issue by elianiva** [folke/todo-comments.nvim#10]
It's quite common for a TODO to have an author, I was using treesitter comment parser and it can highlight the author name inside the parentheses. Currently I use both to make this happen but it would be cool if this plugin can do that as well, thanks! :)

here's a reference:
![image](https://user-images.githubusercontent.com/51877647/118264486-f79f8500-b4e1-11eb-9657-f1dc53dfdcdb.png)

**Comment by shanff** [comment]
Wouldn't this just be a matter of fixing up the regex in the config to cover your use case?

```
 -- regex that will be used to match keywords.
 -- don't replace the (KEYWORDS) placeholder
-- pattern = "(KEYWORDS):",
pattern = "(KEYWORDS)%(.*%)" <-- Don't hold me to this, I don't do much lua
-- pattern = "(KEYWORDS)", -- match without the extra colon. You'll likely get false positives
-- pattern = "-- (KEYWORDS):", -- only match in lua comments
```

**Comment by folke** [comment]
Sounds like a great idea. I'll add it to the list :)

**Comment by goncalves-diogo** [comment]
Hi, i've looked in these problem because i really needed the feature and I've developed regex to get to a result similar to what you expect i think.

In this image you can see the result i got:
![image](https://user-images.githubusercontent.com/33640150/126870979-ad177398-fced-4470-8a3f-58ada9a8d173.png)


I got the previous result with the following property on setup:
```
require("todo-comments").setup {
    highlight = {
      before = "", -- "fg" or "bg" or empty
      keyword = "bg", -- "fg", "bg", "wide" or empty. (wide is the same as bg, but will also highlight surrounding characters)
      after = "fg", -- "fg" or "bg" or empty
      pattern = [[.*<(KEYWORDS)(\([^\)]*\))?:]],
      comments_only = true, -- uses treesitter to match keywords in comments only
      max_line_len = 400, -- ignore lines longer than this
      exclude = {}, -- list of file types to exclude highlighting
    },
    search = {
        command = "rg",
        args = {
            "--color=never",
            "--no-heading",
            "--with-filename",
            "--line-number",
            "--column",
        },
        pattern = [[\b(KEYWORDS)(\([^\)]*\))?:]],
    },
}
```

**Comment by knpwrs** [comment]
I think there has been a change to the highlighting logic to swallow the `:`, or whatever character comes after the keyword, because this is what I see with the custom regex solution:

![image](https://user-images.githubusercontent.com/174864/133630380-0f7c74c8-ca8f-4772-a566-7606827d1eba.png)

That text is:

```
TODO: foobar
TODO(kp): delete the below once ...
```

**Comment by dav1d-wright** [comment]
bumping this feature request because I am also looking for a way to do this :slightly_smiling_face:

**Comment by Rukenshia** [comment]
just stumbled across this while trying to figure out how to achieve it - would love to see this be a feature out of the box

**Comment by GoNZooo** [comment]
I can confirm that this is fixed by #180

**Comment by alexmozaidze** [comment]
It'd be nice if #180 was merged into the master branch

**Comment by bluebrown** [comment]
For completeness. It works now like this as shown in the PR.

```lua
require("todo-comments").setup({
  search = { pattern = [[\b(KEYWORDS)(\([^\)]*\))?:]] },
  highlight = { pattern = [[.*<((KEYWORDS)%(\(.{-1,}\))?):]] },
})
```
