### ISSUE TITLE
No highlight

### ISSUE THREAD

**Issue by bouteillerAlan** [folke/todo-comments.nvim#103]
Hello, I want to use this plugin but when I install it  nothing append. I'm pretty new to neovim so I'm pretty sure it's a mistake of my own.

I test the plugin in `.ts` file : 
![Screenshot_20220406_145025](https://user-images.githubusercontent.com/30547569/161979307-604a557a-3269-4055-a28f-50dc06346f61.png)

`:TodoTelescope` give nothing too : 
![Screenshot_20220406_145045](https://user-images.githubusercontent.com/30547569/161979396-8544db41-fd63-48db-9af0-4276b391f767.png)

I have installed the plugin via Plug : 
`~/.config/nvim/plug.vim`
```
Plug 'nvim-lua/plenary.nvim'
Plug 'folke/todo-comments.nvim'
```
And in my config file : 
`~/.config/nvim/after/plugin/todo-comment.rc.lua`
```
require("todo-comments").setup {}
```
I have Telescope and ripgrep too. 
My config repo : [https://github.com/bouteillerAlan/nvim-dotfile](https://github.com/bouteillerAlan/nvim-dotfile)

**Comment by JustGenius-s** [comment]
It looks like you write them in a wrong way, just try this:

>`TODO:`
 `WARN:`
`HACK:`
`FIXME:`

Don't forget  to add a `;` after any tag :)

**Comment by Imnaseli** [comment]
Add a : after the TODO.
like 
//TODO:
