### ISSUE TITLE
[Help] Showing the telescope todo-comments panel with a single `require` statement

### ISSUE THREAD

**Issue by pidgeon777** [folke/todo-comments.nvim#105]
What I'm trying to achieve, is to display the telescope panel for todo-comments, as done with `Telescope todo-comments todo`, but using the `require` statement, instead. So, something like this:

```lua
:lua require("telescope._extensions.todo-comments").todo(opts)
```

The line above returns an error. What should be the correct way to achieve that? So that I'll be able to configure the telescope panel layout and sorting strategies even for todo-comments.

Regards

**Comment by riddlew** [comment]
```lua
:lua require("telescope._extensions.todo-comments").exports.todo(opts)
```
