### ISSUE TITLE
Bug: Attempt to concatenate field `rg_regex` (a nil value)

### ISSUE THREAD

**Issue by Shivansh-007** [folke/todo-comments.nvim#11]
Hey folke firstly thanks for this amazing plugin!

Whenever I do `:TodoQuickFix` or any other command of this plugin, I get stuck on this error. Not sure if it is a problem on my end or a bug with the plugin, but yeah I need some help with this.

### Bug
![Screenshot from 2021-05-14 17-18-09](https://user-images.githubusercontent.com/69356296/118266593-742d6600-b4d8-11eb-9418-f715873326b9.png)

### Config
![Screenshot from 2021-05-14 17-21-19](https://user-images.githubusercontent.com/69356296/118266860-d1c1b280-b4d8-11eb-8e15-d0a4fb3ee7e4.png)

I am using the same config that you showed in the README.md as an example.

**Comment by folke** [comment]
That's odd. It would give that error if setup wasn't run. Also, you don't need to provide any options if you want the defaults.

How do you load the plugin? With packer?  Make sure the setup is in the config packer setting

**Comment by Shivansh-007** [comment]
Yes, I use packer

![Screenshot from 2021-05-14 17-38-06](https://user-images.githubusercontent.com/69356296/118268616-3a119380-b4db-11eb-8380-b5b744c2cf5d.png)

**Comment by folke** [comment]
The setup should be in the use clause.

I'm not at home, but something like this:

```lua
use { "folke/todo-comments.nvim", config = function() require("todo-comments").setup() end}
```

**Comment by Shivansh-007** [comment]
> The setup should be in the use clause.
> 
> I'm not at home, but something like this:
> 
> ```lua
> use { "folke/todo-comments.nvim", config = function() require("todo-comments").setup() end}
> ```

Nope the same error still.

**Comment by folke** [comment]
I've just added some additional error logging if things aren't properly loaded. Can update and try again and see what you get?

**Comment by Shivansh-007** [comment]
Looks there is something is wrong with the lazy loading of Todo comments.

### Without `require("todo-comments.config")._setup()`
![Screenshot from 2021-05-14 22-07-38](https://user-images.githubusercontent.com/69356296/118301730-09dceb80-b501-11eb-833d-e8a44f75cdd2.png)


### With `require("todo-comments.config")._setup()`
![Screenshot from 2021-05-14 22-10-43](https://user-images.githubusercontent.com/69356296/118301944-40b30180-b501-11eb-950c-c6df1660dd70.png)

**Comment by folke** [comment]
Did you do PackerCompile and vim restart?

**Comment by Shivansh-007** [comment]
> Did you do PackerCompile and vim restart?

Yep

**Comment by folke** [comment]
That's so odd. And you don't get any errors  during loading right? `:messages`?

If you add a `print` inside that config, it gets printed?

**Comment by Shivansh-007** [comment]
Nope, no messages can be found. and yeah I can `print` inside `pluginList.lua`.

![Screenshot from 2021-05-15 06-28-07](https://user-images.githubusercontent.com/69356296/118343449-bee5c700-b546-11eb-95ea-3f8dd33fa09f.png)

**Comment by folke** [comment]
I meant print inside the config:

```lua
use { "folke/todo-comments.nvim", config = function()
print("inside todo comment config")
require("todo-comments").setup()
end}
```

It really seems as if the config is not executed.

Before running `PackerCompile`, you need to exit vim. I've noticed there's something funky going on with the compile these days.

You could also check the compiuled code and see if the setup is actually there.

I suspect this is the issue you're having.

**Comment by folke** [comment]
See also this https://github.com/wbthomason/packer.nvim/issues/304

**Comment by Shivansh-007** [comment]
> ```lua
> use { "folke/todo-comments.nvim", config = function()
> print("inside todo comment config")
> require("todo-comments").setup()
> end}
> ```

Weird, that works now 🤔

**Comment by folke** [comment]
Great, must've been the compile that didn't work. It's a bit weird that you need to exit vim before doing a recompile.

**Comment by Shivansh-007** [comment]
Another question, can I move the `require("todo-comments").setup()` to another file, or in `init.lua`?

**Comment by folke** [comment]
most people make a directory `lua/config`. Then you can mnake `lua/config/todo-comments.lua`
Put your setup stuff there and then:

```lua
use { "folke/todo-comments.nvim", config = function() require("config.todo-comments") end}
```

**Comment by Shivansh-007** [comment]
> most people make a directory `lua/config`. Then you can mnake `lua/config/todo-comments.lua`
> Put your setup stuff there and then:
> 
> ```lua
> use { "folke/todo-comments.nvim", config = function() require("config.todo-comments") end}
> ```

Alright thanks!
