### ISSUE TITLE
[DOCS] Does todo-comments Not Have `:help` Entries?

### ISSUE THREAD

**Issue by TheCedarPrince** [folke/todo-comments.nvim#114]
Hi @folke !

I absolutely love this plugin and have been using it everyday. Has really improved my workflow as well as added a nice bit of aesthetic pizzazz to my editor! :sparkles: 

However, I was a bit confused when I attempted to run `:help todo-comments` and was surprised to see no help available for the plugin. Does it not exist? If so, would it be possible to add some in using a tool such as: https://github.com/numToStr/lemmy-help ? 

Either way, thanks for the great plugin and have a wonderful day! 

~ tcp :deciduous_tree:

**Comment by folke** [comment]
It has now :)

**Comment by TheCedarPrince** [comment]
Amazing! Your plugins just keep getting better and better @folke - have a wonderful day!
