### ISSUE TITLE
pattern option does not work

### ISSUE THREAD

**Issue by mateusz834** [folke/todo-comments.nvim#118]
```
require("todo-comments").setup({    
    highlight = {    
        before = "fg",     
        keyword = "fg",    
        pattern = [[.*<(KEYWORDS)\s*]],     
    },    
    pattern = [[\b(KEYWORDS)]],     
})    
```
I just removed the colon from the default values of pattern. 

```
//TODO: works
//TODO not really
```

The highlight works as expected, but all the `:Todo(..)` commands only show the first todo.

**Comment by Karmenzind** [comment]
This works.  https://github.com/folke/todo-comments.nvim/issues/80#issuecomment-1082469859

**Comment by mateusz834** [comment]
@Karmenzind Thanks
