### ISSUE TITLE
[Feature Request]: support comments in latex files

### ISSUE THREAD

**Issue by Pyons** [folke/todo-comments.nvim#12]
It would be awesome if this plugin would support comments in latex files.

I haven't looked into the code yet. But would be willing to create PR.

Great plugin!

**Comment by Mike325** [comment]
This pull request #8 should be halfway fix for this, by default latex settings include `:` in the `iskeyword` setting which makes the default regex fail `<(KEYWORDS)>:`, as a quick workaround you could either change the setting to `setlocal iskeyword-=:` inside `after/ftplugin/tex.vim` or change the `hl_regex` option to something like `(KEYWORDS):`

**Comment by Pyons** [comment]
Thank you for your workaround. Works :+1:
