### ISSUE TITLE
Multi-line todo comment text colouring

### ISSUE THREAD

**Issue by tjzegmott** [folke/todo-comments.nvim#125]
Currently if a todo-comment is written over multiple lines only the line with the pattern (eg INFO, TODO, ...) is coloured.

ie in the example below only the first line is coloured:
```
# TODO: check if the file is the only copy while there needs to be at least one copy
#             according to the replication policy.
```

It would be nice if both lines were coloured.

**Comment by mrjones2014** [comment]
duplicate of #37

**Comment by Integralist** [comment]
I actually have found this to be a good thing because it forces me to write concisely a 'title' and then all following lines are my extra context. Just my two cents.

**Comment by folke** [comment]
I just pushed an update that implements this
