### ISSUE TITLE
Feature request: Add the "DBG" codetag or a way to add custom codetags

### ISSUE THREAD

**Issue by ZiViZiViZ** [folke/todo-comments.nvim#128]
My team and I like to use the `DBG` codetag (`// DBG:`) at the end of lines of code that are meant only for debugging, such as, various print statements of variables or calculating the expected value of something...

So I was looking to add this codetag to the list of codetags `todo-comments`

**Comment by folke** [comment]
Have you actually checked the documentation? Simply add a new keyword `DBG` to the `keywords` key in the config
