### ISSUE TITLE
[BUG] Wrong highlighting when appending a comment before a todo

### ISSUE THREAD

**Issue by ThomasFrans** [folke/todo-comments.nvim#134]
The for in the next image shouldn't be highlighted, and it isn't when I reload the file. The reason it highlights is because I just added an extra comment above it. The todo highlight probably needs to be updated when a line is appended above or something...
Wrong:
![image](https://user-images.githubusercontent.com/48214567/192097309-3a584666-bdca-4aa3-b422-7e0ef5329c10.png)

Correct:
![image](https://user-images.githubusercontent.com/48214567/192097394-ed99886a-d6e0-451c-b540-0c91d0214011.png)

**Comment by mr-majkel** [comment]
What I have observed is that deleting lines above the comment is not messing things up. However, if you add one or more lines above the highlighted comment, the highlight is activated on the line below a "TODO"-like comment. Inserting characters on the line with a "TODO" like comment fixes the highlight for the particular line (as does reloading of the buffer as @ThomasFrans mentioned)

![image](https://user-images.githubusercontent.com/9008816/195566448-7cb9097b-87ae-4dea-8597-f6577bd03904.png)
![image](https://user-images.githubusercontent.com/9008816/195566537-d614f085-b309-4125-bb30-e6762269e390.png)
![image](https://user-images.githubusercontent.com/9008816/195567067-fb6167f0-a2f1-493c-8eca-366568db7718.png)

**Comment by judaew** [comment]
This also breaks the code highlighting:
<img width="486" alt="Screen Shot 2022-11-05 at 12 48 28" src="https://user-images.githubusercontent.com/41125715/200116251-8ef631ec-646e-4cb3-bdab-84dee4d41069.png">

**Comment by judaew** [comment]
This does not fix for non-treesister based highlighting.

**Comment by folke** [comment]
@judaew are you sure? I don't think the issue happens for non-treesitter highlighting. The issue is cause by the async nature of teesitter. We render the highlights before treesitter knows a certain node is a comment.

**Comment by judaew** [comment]
I have this problem with [macports.nvim](https://github.com/judaew/macports.nvim) which does not use treesister.

**Comment by judaew** [comment]
Just FYI: This is now fixed.
