### ISSUE TITLE
Show for current buffer

### ISSUE THREAD

**Issue by Integralist** [folke/todo-comments.nvim#136]
Does anyone know if it's possible to only see the items (todos/notes/warnings etc) for the current file?

This might be possible, but if so I couldn't tell from the README or the help documentation.

Thanks!

**Comment by kagbodji** [comment]
I was looking for this as well, and can't find a way to do it. Looking through the source, I don't think this is currently possible. Can this be a feature request, where we can specify `currbuf=true` similar to `cwd/keyword`?

**Comment by Camille-Upway** [comment]
I think you can achieve that with the solution from issue https://github.com/folke/todo-comments.nvim/issues/110.

**Comment by Integralist** [comment]
BTW this was what I ended up using...

```lua
vim.keymap.set("n", "<leader>da", "<Cmd>TodoTelescope<CR>", {desc = "search TODOs across all files"})
vim.keymap.set("n", "<leader>dc", "<Cmd>exe ':TodoQuickFix cwd=' .. fnameescape(expand('%:p'))<CR>", {desc = "search TODOs in current file"})
```

**Comment by addz** [comment]
Thanks for this @Integralist! I was looking for something like this too. Passing in the current file to the existing command on a key bind works great!

BTW for future ppl, if you also want a mapping to show trouble Diagnostics for the current buffer only, check out the Examples doc  - https://github.com/folke/trouble.nvim/blob/main/docs/examples.md#filtering.

**Comment by addz** [comment]
oh, btw, I just finally updated to Trouble 3.x version and no need to do the above anymore, Trouble has sweet filtering now..

e.g. `Trouble todo toggle filter.buf=0` to restrict matches to current buffer. :wink: 

@folke - you can probably close this issue now - Thanks for the great integrations between (your) plugin's! :heart:
