### ISSUE TITLE
How to change the Telescope theme?

### ISSUE THREAD

**Issue by n1ghtmare** [folke/todo-comments.nvim#137]
Is there a way to change the Telescope layout theme to (for example) Ivy? If yes - how?

**Comment by zSnails** [comment]
Hi, I don't know if you still need help with this, but maybe someone else can find this useful.

You can specify a theme when invoking the `TodoTelescope` command.

```vim
:TodoTelescope theme=dropdown
```

**Comment by RAprogramm** [comment]
`:TodoTelescope theme=ivy initial_mode=normal previewer=false layout_config={bottom_pane={height=12}}`
i set this in my keybindings with "which-key" and it works great

**Comment by n1ghtmare** [comment]
Thank you so much @zSnails & @RAprogramm ! This solved my issue!
