### ISSUE TITLE
Error executing lua callback: Keyboard interrupt

### ISSUE THREAD

**Issue by lmapii** [folke/todo-comments.nvim#140]
I've installed todo-comments and I'm seeing this error message when I'm going back to normal mode from insert mode using `<C-c>`. I'm not really familiar with lua so I wouldn't know how to debug this problem, but I'd like to submit it nevertheless:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/7037131/194591547-2ec2c73a-915a-4749-8d5f-9bfa73c84dad.png">

The exact actions that I'm performing are:
* Navigate to a code block with `{}` 
* Execute `ci{`
* Immediately try to go back to normal mode using `<C-c>`

Previously I had `<C-c>` mapped to `<Esc>` and I didn't seem to have this problem then.

**Comment by lmapii** [comment]
I just hit another bump, remapping `<c-c>` to `<Esc>` is actually a very bad idea since it doesn't allow you to quit the buffer that is displayed when using `q:` (see last commands). I'm very new to vim so it is still very hard to tell which mappings make sense and which ones don't.

**Comment by meomeo187** [comment]
Hello, looks like the same Issue mentioned in  [Issue #73](https://github.com/folke/todo-comments.nvim/issues/73) and [neovim Issue #16416](https://github.com/neovim/neovim/issues/16416) :thinking:?
The mode for your remapping should be the insert mode, right? I have no problems with this and can  leave the command history with it.

```lua
function Set_Keymap(mode, lhs, rhs)
	local opts = { noremap = true, silent = true }
    vim.keymap.set(mode, lhs, rhs, opts)
	vim.api.nvim_set_keymap(mode, lhs, rhs, opts)
end

Set_Keymap("i", "<C-c>", "<Esc>")
```

**Comment by lmapii** [comment]
Looks suspiciously like the mentioned issue. Yeah I've just blindly remapped visual and normal mode too, if I only map it to the insert mode it actually looks good :)
