### ISSUE TITLE
Comments found and highlighted but not appearing in listings

### ISSUE THREAD

**Issue by HoloTheDrunk** [folke/todo-comments.nvim#144]
`todo-comments` finds the comments properly but they do not show in any of the lists (not Loc, QuickFix, Telescope nor Trouble).

**Error message**
![Error message](https://user-images.githubusercontent.com/45125768/195964182-35b5ad77-dc01-43d2-ba8f-969e42221803.png)
**Code sample used where FIXMEs are detected and highlighted (bottom window is Trouble)**
![Code sample used where FIXMEs are detected and highlighted](https://user-images.githubusercontent.com/45125768/195964190-0fa83f62-152b-4864-bcc3-22f9d24ed3b0.png)

Neovim version: 0.8

**Comment by eduardomcv** [comment]
I'm having the same issue: `todo-comments` highlights keywords but they don't show up in any list.

Additionally, when I call `require('todo-comments').jump_next()` or `require('todo-comments').jump_prev()`, if a keyword is available, I'm getting this stack trace:
![Screenshot 2022-10-30 at 20 44 06](https://user-images.githubusercontent.com/45357456/198900710-43d878c1-b140-4dcb-9952-24527b8503a1.png)
If there's no keywords, it works as intended and I get `No more todo comments to jump to`.

I'm using nvim 0.8. Here's my config if it helps:
```lua
require("todo-comments").setup {
  keywords = {
    DELETEME = {
      icon = "",
      color = "#ff0000",
    },
    FIXME = {
      icon = "",
      color = "#fff400",
    },
    HACK = {
      icon = "",
      color = "#00f9ff",
    },
    TODO = {
      icon = "",
      color = "#ed00ff",
    },
    WIP = {
      icon = "",
      color = "#ff7C00",
    }
  },
  merge_keywords = false,
}
```

**Comment by midoBB** [comment]
The weird thing about this in my case was that TodoTelescope was working correctly, but TodoTrouble / TodoQuickfix both didn't.

**Comment by folke** [comment]
@midoBB that's interesting. Are you using the default config? Can you give me an example with a comment that shows with Telescope, but not with the  other commands?

**Comment by midoBB** [comment]
This is my config at the moment. To be noted that if I don't include this pattern the Telescope search doesn't find the Todo comments.
```lua
local status_ok, trouble = pcall(require, "trouble")
if not status_ok then
  return
end
trouble.setup {
    mode = "workspace_diagnostics",
    fold_open = "",
    fold_closed = "",
    auto_jump = { "lsp_definitions" },
    auto_fold = true,
    use_diagnostic_signs = true,
}
local status_ok, todo = pcall(require, "todo-comments")
if not status_ok then
  return
end
todo.setup {
  signs = true,
  search = {
    pattern = [[\b(KEYWORDS)\b]]
  }
}

```

**Comment by folke** [comment]
The default higlight pattern requires a `:`, so I guess that's your issue?

**Comment by midoBB** [comment]
I'm so sorry for troubling you. Yes, adding a column seemed to fix both.

**Comment by folke** [comment]
@HoloTheDrunk did you change any of the patterns? highlight and search pattersn have a different syntax, so make sure you make them behave the same

**Comment by IlyasYOY** [comment]
I have the same issue. 

Are there any updates on this?

**Comment by dawnchan030920** [comment]
I'm also confronted with the problem and adding `--hidden` doesn't work for me. Also, when I run `jump_next()` it says that there're no more todos.
i'm using `lazy` & `nvchad` and here is my code in `custom/plugins.lua` related to `todo-comments` 
```
{
  "folke/todo-comments.nvim",
  dependencies = {{"nvim-lua/plenary.nvim"}},
  init = function()
    require("core.utils").lazy_load "todo-comments.nvim"
  end,
  config = function (_, opts)
    require("todo-comments").setup(opts)
  end,
},
```
![todo-comments list无法显示（可以高亮）](https://github.com/folke/todo-comments.nvim/assets/31147639/f28190f7-60a9-46d4-87a6-5249f995dfb6)
![todo-comments list无法显示2（可以高亮）](https://github.com/folke/todo-comments.nvim/assets/31147639/804e636c-ea03-4494-a1fa-cff3b4521738)

**Comment by arturxdev** [comment]
i have the same issue

**Comment by PBHDK** [comment]
Same issue for me too. TODO comments are highlighted, but the quickfix list, which I'm opening with a Telescope mapping, not with `TodoTelescope`, remains empty. Running`TodoQuickfix` then populates it with values and I can access it with my dedicated Telescope mapping.

@folke, do you maybe have some pointers for us? Or is this by design?

**Comment by calvinchoy** [comment]
I notice that I have this issue with specific files. Everything works fine in for example my vue/js/ts files but NOT in lua. Highlights showing up correctly but not listing in for example TodoTelescope.

**Comment by goombaActivist** [comment]
@calvinchoy   I fixed the issue by appending "--no-ignore-vcs" to the key search in opts
```lua
search = {
    command = "rg",
    args = {
        "--color=never",
        "--no-heading",
        "--with-filename",
        "--line-number",
        "--column",
        "--no-ignore-vcs",
    },
}

```
I had similar problems with telescope-live-grep not working in some projects and that fixed as well

**Comment by calvinchoy** [comment]
> @calvinchoy   I fixed the issue by appending "--no-ignore-vcs" to the key search in opts/require('todo-comments').setup()
> 
> ```lua
> 
> search = {
> 
>     command = "rg",
> 
>     args = {
> 
>         "--color=never",
> 
>         "--no-heading",
> 
>         "--with-filename",
> 
>         "--line-number",
> 
>         "--column",
> 
>         "--no-ignore-vcs",
> 
>     },
> 
> }
> 
> 
> 
> ```
> 
> I had similar problems with telescope-live-grep not working in some projects and that fixed as well

Excellent, thanks!
