### ISSUE TITLE
1814fec breaks highlighting?

### ISSUE THREAD

**Issue by timtro** [folke/todo-comments.nvim#147]
I'm not sure why but [1814fec](https://github.com/folke/todo-comments.nvim/commit/1814feca54540497de99d474dd6c9de6b691cf01) on highlight.lua:92 breaks highlighting on both of my machines. The word TODO: is highlighted from T to O, not including the colon. The highlight colour is pale yellow (using TokyoNight) and only TODO and FIXME and no other hot-words are highlighted.

From https://github.com/folke/todo-comments.nvim/commit/41dd70e581ff4a4c3512c5e1f3d063b00f68cc16, changing highlight.lua:92 like so:
```
92    and M.is_comment(buf, lnum, start - 1)
```
(that is, removing not from M.is_comment) restores behaviour to what I am used to. But I'm not sure what new functionality is broken by the fix (if any).

**Comment by folke** [comment]
Can you give an example source code that shows the issue?

**Comment by folke** [comment]
Also, what is your todo-comments setup?

**Comment by folke** [comment]
The pale yellow is not todo-comments. That's treesitter comment parser.

I need to know the filetype and the treesitter parser it uses.

**Comment by folke** [comment]
and example code

**Comment by timtro** [comment]
Sorry, @folke. I know better than to post a lame bug report. I was tired and assumed, *for some silly reason*, that the issue would be readily reproducible.

I knew the pale yellow wasn't from todo-comments, but I didn't know it was from treesitter. That's good to know.

Starting from today's 530eb3a … Well s***. It works now. Either today's commit fixed it for me, or the problem was an interaction with one of my other plugins that got updated.

I'm terribly sorry for the trouble. But thanks for your time. And of course, thanks for all of your plugins. You make my workflow much more enjoyable. I use no less than 6 of your plugins.

**Comment by timtro** [comment]
Sorry, @folke. I know better than to post a lame bug report. I was tired and assumed, *for some silly reason*, that the issue would be readily reproducible.

I knew the pale yellow wasn't from todo-comments, but I didn't know it was from treesitter. That's good to know.

Starting from today's 530eb3a … Well s***. It works now, but only for python and LaTeX?

## Config.

I removed custom configuration for simplicity:
```
require('todo-comments').setup {}
```
This is called a file `after/plugin/todo-comments.lua`.
I don't have any crazy after/ft stuff that should cause issues.

I have TS plugins installed for each of the languages in the below examples.
I have LSP servers running for Python, Lua and C++ in the examples below.

I don't expect you to debug my config, so if nothing jumps out to you as obvious, I'll fall back to a minimal config and rebuild it until I find the issue. But any direction for debugging would be appreciated. Are there any known conflicts?

## Examples:

These are examples in the languages I commonly use.

Python:
![python](https://user-images.githubusercontent.com/329007/198687378-0e844ef6-8af2-46f4-884c-cc89fa8a482a.png)

LaTeX:
![latex](https://user-images.githubusercontent.com/329007/198689310-578c4338-33fc-4d92-ad97-04a4a00b2d83.png)

Lua:
![lua](https://user-images.githubusercontent.com/329007/198687536-0ca06139-3eac-4962-9b87-a685e9eca6f0.png)

C++:
![cpp](https://user-images.githubusercontent.com/329007/198687563-9d57025a-8a04-4a11-9f69-82b24084b89d.png)

Haskell:
![haskell](https://user-images.githubusercontent.com/329007/198687584-e8b4f0c9-244c-4fc9-a430-6443b16bf831.png)

Rust:
![rust](https://user-images.githubusercontent.com/329007/198687602-dc5ec13d-b247-4fa0-8672-6e86b2399910.png)

GO:
![go](https://user-images.githubusercontent.com/329007/198687619-7aba201c-f12c-4eae-9cae-38a56ad9adaf.png)

I'm terribly sorry for the trouble. But thanks for your time. And of course, thanks for all of your plugins. You make my workflow much more enjoyable. I use no less than 6 of your plugins.

## Versions

Both machines are on Ubuntu 22.04.1 LTS.

```
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-OtIsyZ/neovim-0.9.0~ubuntu1+git202210271433-5cf820f38-333b5866f=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-OtIsyZ/neovim-0.9.0~ubuntu1+git202210271433-5cf820f38-333b5866f/build/cmake.config -I/build/neovim-OtIsyZ/neovim-0.9.0~ubuntu1+git202210271433-5cf820f38-333b5866f/src -I/build/neovim-OtIsyZ/neovim-0.9.0~ubuntu1+git202210271433-5cf820f38-333b5866f/.deps/usr/include -I/usr/include -I/build/neovim-OtIsyZ/neovim-0.9.0~ubuntu1+git202210271433-5cf820f38-333b5866f/build/src/nvim/auto -I/build/neovim-OtIsyZ/neovim-0.9.0~ubuntu1+git202210271433-5cf820f38-333b5866f/build/include
Compiled by buildd@lcy02-amd64-047

Features: +acl +iconv +tui
```

**Comment by folke** [comment]
Your Lua screenshot is for sure **not** using Treesitter. Do you have `additional_vim_regex_highlighting=true` by any chance? You shouldn;t  use that option.

I've been troubleshooting a similar problem with another user earlier today. His problem was eventually a broken color scheme, but the troubleshooting tips shold be useful: https://github.com/folke/todo-comments.nvim/issues/148

Would be interested to get the result of those commands for the lua file

**Comment by ExpandingMan** [comment]
I'm seeing this to.  It looks like it's still working properly for languages in which I have treesitter highlighting but is breaking for languages for which I do not have treesitter highlighting.  This occurs for both values of `additional_vim_regex_highlighting` (which I had set to `true` before and it did not break todo-comments until the recent commit).

**Comment by timtro** [comment]
> Your Lua screenshot is for sure **not** using Treesitter. Do you have `additional_vim_regex_highlighting=true` by any chance? You shouldn;t use that option.

Too right you are: I switched computers to make the screencaps and I didn't have the Lua TS installed. I just did, and it didn't make a difference.

> I've been troubleshooting a similar problem with another user earlier today. His problem was eventually a broken color scheme, but the troubleshooting tips shold be useful: #148
> 
> Would be interested to get the result of those commands for the lua file

Will do ASAP. Expect results in the next couple of hours.

**Comment by timtro** [comment]
Alright. As embarrassing as it is for me to admit this, the problem was my treesitter config. I don't know if things have version-drifted in the ages since I wrote the setup, or if I didn't do it right in the first place. Either way, I'm very sorry to have wasted your time, @folke.

The issue that you referenced (#148) was very helpful in identifying that the problem was my treesitter setup. From there, the fix was simply getting the default config from the nvim-treesitter README, working my customizations back into it, and poof.

Please accept my sincere thanks and apologies.

P.S. Now also using `additional_vim_regex_highlighting=false`, just in case.

**Comment by folke** [comment]
Glad you have it working!

**Comment by ExpandingMan** [comment]
I'm a bit confused.  Was it never intended for it to work with non treesitter highlighting if `comments_only=true`?
