### ISSUE TITLE
TodoTelescope doesn't search dotfolder subdirectories

### ISSUE THREAD

**Issue by BigDru** [folke/todo-comments.nvim#149]
My Telescope plugin is setup so that it searches dotfolders in the cwd. If I use live_grep I find the todos I'm looking for. 
However, this plugin seems to ignore these subdirectories. 
At the very least there should be a default option in the setup to change the search scope.

**Comment by gilitos92** [comment]
Add the `--hidden` flag to the ripgrep command in the setup configuration table:
```       
search = { 
  args = {
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--hidden"
  }
}
```

**Comment by BigDru** [comment]
Thank you!
