### ISSUE TITLE
got inconsistent results from todotelescope and other methods

### ISSUE THREAD

**Issue by bryceyang** [folke/todo-comments.nvim#15]
In the same nvim instance, the result of todotelescope is different from todotrouble and todoquickfix.

todotrouble:
<img width="312" alt="Screen Shot 2021-05-15 at 3 43 08 PM" src="https://user-images.githubusercontent.com/9302617/118352479-4148a800-b594-11eb-994d-efe60b3ea62d.png">

todoquickfix:

<img width="500" alt="Screen Shot 2021-05-15 at 3 44 16 PM" src="https://user-images.githubusercontent.com/9302617/118352508-69380b80-b594-11eb-9550-45c535518bc7.png">

todotelescope:
<img width="955" alt="Screen Shot 2021-05-15 at 3 43 36 PM" src="https://user-images.githubusercontent.com/9302617/118352485-51608780-b594-11eb-8d60-3e847ab93e38.png">

**Comment by folke** [comment]
Are you getting this consistently? Meaning if you close vim and try again, you see the exact same inconsistencies?

Under the hood the different methods all use the same code to run `rg` and get the results.

**Comment by folke** [comment]
I suspect there might've been an issue with stdout pipes from ripgrep being closed before fetching all the results with `libuv`.
I've changed the implementation to use the `plenary.job` classes instead. Adds an extra dependency on `plenary`, but will at least make sure that we handle any possible edges cases with `libuv`.

Do let me know if you'd still get any inconsistencies.

**Comment by folke** [comment]
so I was wrong, Telescope did not use the internal method.

Either way, would be great if you could test with the latest changes. I'm fairly confident that whatever was causing the discrepancies, is fixed now.

**Comment by folke** [comment]
Closing this as it should be fixed. If this is not the case, feel free to reopen this issue.
