### ISSUE TITLE
Does not work on markdown files?

### ISSUE THREAD

**Issue by alexandre-julien** [folke/todo-comments.nvim#150]
I love this plugin so far and was about to implement something similar myself before I found it.
It just seems to not work on markdown files ?

**Comment by jose8a** [comment]
I'm seeing that all of the keywords that are supposed to be highlighted are all the same color even if I copy over the complete example configuration for "keywords" and "colors" from the plugin README. The different highlight colors work in fine in non-markdown files, and they even work in files without a file-extension.

**Comment by folke** [comment]
Todo comments was broken for non-treesitter files. So it only worked in markdown files if you had the `markdown` and `markdown_inline` treesitter parser istalled.

I just fixed it so it should also work in markdown files without treesitter.

Be aware, that by default highlighting will only work in comments. Check the config to change this. So for markdown, it will only highlight todo comments inside `<!-- TODO: foooo -->`
