### ISSUE TITLE
Regression introduced in e90b17e

### ISSUE THREAD

**Issue by antonk52** [folke/todo-comments.nvim#154]
Hi and thank you for your plugin!

I've noticed today that my neovim would frequently freeze when navigating within files. Pressing `jjjjjjjjj` would make it hang for up to 10 seconds. I was able to narrow down the problem to this plugin. Interestingly enough if I roll it back to before e90b17e it completely fixes the problem.

This problem is easier to reproduce with a really large file with a lot of comments. Here is a good example [`vscode/index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts).

**Comment by folke** [comment]
Redraws are now throttled. This should fix your issue. Would be great if you can confirm. Thanks!

**Comment by antonk52** [comment]
Thanks for the prompt response. I've just checked and it no longer hangs. Thank you!
