### ISSUE TITLE
Bug: Error executing vim.schedula lua callback

### ISSUE THREAD

**Issue by Chaitanyabsprip** [folke/todo-comments.nvim#16]
![Screenshot:2021-05-15_000](https://user-images.githubusercontent.com/55058351/118356690-1f4f2580-b594-11eb-85dc-d346071a5aa8.png)

**Comment by folke** [comment]
I just pushed a fix for this. This could only happen for buffers that got deleted for which Nvim didn't call detach. Not sure how this can happen, but I fixed it anyway :)

**Comment by Chaitanyabsprip** [comment]
fixed the issue
