### ISSUE TITLE
Feature Request: exclude comments_only parameter for certain file types

### ISSUE THREAD

**Issue by Normanras** [folke/todo-comments.nvim#160]
This plugin has been hugely important to my dev workflow, but I also take _alot_ of notes in Markdown, and would love to use the same features in those files. Since `md` doesn't have an inherent commenting syntax/structure, I've currently set `comments_only = false`. I just have to remember that when I'm actually programming to put the TODO in a comment.

**Comment by jose8a** [comment]
I was wondering why markdown files was the only place where I couldn't get these to work, and finding your Feature request and the config I needed to set helps me understand why that was. Makes sense. Would love this feature for that reason as well. I too write a ton of markdown files and use these comments as markers for a lot of different things.

**Comment by fgr1986** [comment]
Together with it, it would be lovely if `comments_only` could also be configured per keyword.
For example, `DEBUG`, being also highlighted in code and not in comments.

Thanks!

**Comment by gruvw** [comment]
+1 on this, `comments_only` should really be configured per keyword. It would allow for much more flexibility

**Comment by bigFin** [comment]
See #4 - you can change the regex in your config to omit the :

I still think it would be nice to make this change only for .md files
