### ISSUE TITLE
how to disable todo-comment in some filetype ?

### ISSUE THREAD

**Issue by HUAHUAI23** [folke/todo-comments.nvim#163]
i want to disable todo-comment in some filetype, is there a command provided by todo-comment to disable todo-comment ?

**Comment by RicardoRien** [comment]
I have the same question, As you can see is reading all inside node_modules folder
![image](https://user-images.githubusercontent.com/55299652/210008177-7a62a7fb-717a-4e00-a4fc-f28dc5f79de9.png)

**Comment by RicardoRien** [comment]
You should look at #71 maybe it would help.
