### ISSUE TITLE
comments not highlighted

### ISSUE THREAD

**Issue by jeusdi** [folke/todo-comments.nvim#165]
My Todo comments are not highlighted...

![image](https://user-images.githubusercontent.com/941639/206153879-1fee8ae2-b360-41dc-9d99-1d64353661e2.png)

My current configuration is:

```
use {
      "folke/todo-comments.nvim",
      requires = "nvim-lua/plenary.nvim",
      config = function()
        require("todo-comments").setup()
      end
    }
```
Any ideas?

**Comment by folke** [comment]
You're missing a colon afer TODO and FIXME. check the docs
