### ISSUE TITLE
Error while TreeSitter parser is installed

### ISSUE THREAD

**Issue by Maduki-tech** [folke/todo-comments.nvim#167]
Hello im getting an Error which is followed

![Screenshot 2022-12-14 at 18 19 02](https://user-images.githubusercontent.com/70664223/207663384-4ebaf0c7-c5fc-4722-81ca-66540f0f26f2.png)

I get this error in every File.
The comment is Working when i dont have any Treesitter Parser installed. As soon as i install one i get this error.

Using Neovim 0.8.0

**Comment by folke** [comment]
You are not using 0.8.0. You're prbably using an older dev version of 0.8.0.

Check the requirements. It's literally in the docs
