### ISSUE TITLE
Disable highlighting?

### ISSUE THREAD

**Issue by willeccles** [folke/todo-comments.nvim#168]
Is there a way to disable highlighting completely? All I need is the ability to find and look through my TODOs. I do not want highlighting, signs, etc. Signs can be disabled quite easily, but I would like to be able to disable highlighting as well. Is this possible? I don't see an obvious way to do this in the configuration.

**Comment by folke** [comment]
Change the higlihgt pattern to something that will never match. Searching todos uses another pattern, so that should do the trick!
