### ISSUE TITLE
Bug: Error while calling lua chunk

### ISSUE THREAD

**Issue by onionka** [folke/todo-comments.nvim#17]
Hello,

thanks you for this great plugin, I was searching for such thing for some time now.

Anyway, I wasn't able to initialize it properly. When I added the installation part to the nvim config, I was able to install it via PLUG manager:
```vim
        Plug 'nvim-lua/plenary.nvim'
        Plug 'folke/todo-comments.nvim'

        lua <<EOF
          require("todo-comments").setup {
            -- your configuration comes here
            -- or leave it empty to use the default settings
            -- refer to the configuration section below
          }
EOF
```

But, when I ran the neovim, I received this error:
```
Error detected while processing /Users/mcibulka/.config/nvim/init.vim:
line  423:
E5108: Error executing lua [string ":lua"]:1: module 'todo-comments' not found:
        no field package.preload['todo-comments']
        no file './todo-comments.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/todo-comments.lua'
        no file '/usr/local/share/lua/5.1/todo-comments.lua'
        no file '/usr/local/share/lua/5.1/todo-comments/init.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/todo-comments.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/todo-comments/init.lua'
        no file './todo-comments.so'
        no file '/usr/local/lib/lua/5.1/todo-comments.so'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/todo-comments.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
```
The TODO plugin didn't work. But when I reload the nvim config, it didn't gave me any error and the this plugin worked fine.

Here is the output of nvim --version:
```
❯ nvim --version
NVIM v0.5.0-dev+1321-gc57a85d53
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1621055190565.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Could somebody look at this error please?

Thank you

**Comment by folke** [comment]
It only works on neovim 0.5. your second error shows you didn't properly install the plugin

**Comment by onionka** [comment]
Yes, you're right, I'm sorry, I noticed in the middle of writing that I was not using nightly build, I installed it and tried it there, thats where I got that second error, and king of forgot about the first half. I have rewritten it accordingly.

**Comment by folke** [comment]
The second error means you don't have the plugin installed.

**Comment by folke** [comment]
If you installed nighty afterwards, you probably also need to reinstall the plugs

**Comment by onionka** [comment]
I tried removing the installation statement, running PlugClean, adding it back, running PlugInstall, but it didn't help. Still the same error on startup, and when I run `:source ~/.config/neovim/init.vim`, this plugin starts to work.

Am I missing some installation steps?

**Comment by folke** [comment]
~/.config/neovim/init.vim This path is wrong?
It should be nvim, not neovim

**Comment by onionka** [comment]
That was typo ... I am not running it manually, but I have shortcut, it definitely is not because of wrong path, as it doesn't work when I start new instance of neovim

**Comment by folke** [comment]
I'm sorry, but if you get this error:
```E5108: Error executing lua [string ":lua"]:1: module 'todo-comments' not found:```

Then that can only mean you didn't install the plugin properly.

The error literally means that the plugin could not be found on your plugins path.

**Comment by folke** [comment]
Closing this issue as it seems to be a problem related to configuring nvim.

**Comment by aborzunov** [comment]
I experienced this bug too. It disappeared when I had moved Lua setting chunk at the end of `init.vim`.


I use Vundle and place plugin setting in `init.vim` after `Plugin '...'` line for better readability. For example:

```vim
filetype off                                        " required for Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'                       " Vundle manage Vundle

Plugin 'folke/todo-comments.nvim'
" {{{
lua << EOF
  require("todo-comments").setup {
  }
EOF
" }}}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

```

Placing lua chunk inside `vundle#begin()` and `vundle#end()` was the reason that caused this bug.

**Comment by folke** [comment]
@aborzunov that makes sense. It's only after the end that the plugin is effectively added and when you can do the require

**Comment by Nate-Wilkins** [comment]
Was getting the same issue.

The issue, at least for me, was that I was assuming that configuration could happen before the plugin was loaded bc most, if not all of my plugin configuration, is setup before they're loaded.

A little strange to me but I'm sure there's a reason for this.

Thanks for the plugin! Looking good so far.

**Comment by folke** [comment]
> Was getting the same issue.
> 
> The issue, at least for me, was that I was assuming that configuration could happen before the plugin was loaded bc most, if not all of my plugin configuration, is setup before they're loaded.
> 
> A little strange to me but I'm sure there's a reason for this.
> 
> Thanks for the plugin! Looking good so far.

How could you execute a setup function from a module that you require that is not loaded? That's just Lua. If you don't understand that, there's a number of good lua guides out there to get you started.

**Comment by Nate-Wilkins** [comment]
> A little strange to me but I'm sure there's a reason for this.

Ah it's how Lua configures modules that makes more sense. I'm not familiar with it but I might take a look in the new year! Thanks again :+1:
