### ISSUE TITLE
Counter in statusline

### ISSUE THREAD

**Issue by RAprogramm** [folke/todo-comments.nvim#172]
Anybody have idea how to realize counter in lualine?

**Comment by IlyasYOY** [comment]
Hello @RAprogramm 

I assume that you can reuse [this](https://github.com/folke/todo-comments.nvim/blob/main/lua/todo-comments/search.lua#L45) function.

**Comment by RAprogramm** [comment]
Privet @IlyasYOY 

Easier said than done. at real time i don't have enough knowledge and skills to rewrite this function to count the numbers of occurrences instead of adding them to the table. (in my head now only - if "TODO" then count++)

esli est' idei kak sdelat eto - podelis'

**Comment by RAprogramm** [comment]
Easier say than done. At real time I nave not enough knowledge and skills to do that. In my head only - if TODO then count++. 
I don't want to make same function as we have in this plugin (because it will be duplicate of code I think) . I want to know how to get a count of already we have a list of todos

**Comment by folke** [comment]
I you want to add that to the statusline, then you'll need to create a function that properly throttles those calls. You don't wan to do those searches 100 if times per second.

As suggested, you can use that search function for that, but the implementation is on you.

**Comment by RAprogramm** [comment]
```
local function count()
  return require('todo-comments.search').search(
    function(results) print(#results) end
  )
end

print(count())
```
this will print number of todos.

but this
```
local function count()
  return require('todo-comments.search').search(
    function(results) return #results end
  )
end

print(count())
```
will return nothing! why? i need this number and it will done. what is my problem?

**Comment by folke** [comment]
That function is asynchronous, so it doesn't work like that
