### ISSUE TITLE
bug: Telescope fails to run

### ISSUE THREAD

**Issue by hinell** [folke/todo-comments.nvim#175]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-9b1112c

### Operating system/version

Linux Kubuntu 22.04

### Describe the bug

https://github.com/folke/todo-comments.nvim/blob/077c59586d9d0726b0696dc5680eb863f4e04bc5/lua/telescope/_extensions/todo-comments.lua#L65-L67
Because there is no `todo-comments` picker exported by the code above, the following fails 
```
:Telescope todo-comments
```

The following works however:
```
:Telescope todo-comments todo
```

### Steps To Reproduce

Just run in commandline:

```
:Telescope todo-comments
```

### Expected Behavior

Telescope picker is opened as described by docs.

**Comment by folke** [comment]
The docs describe the `TodoTelescope` command

**Comment by hinell** [comment]
@folke  Well `Telescope todo-comments` is much more conveniet.
