### ISSUE TITLE
Is there a way to have the labels case insensitive?

### ISSUE THREAD

**Issue by Mupu** [folke/todo-comments.nvim#177]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-694+g6134c1e8a

### Operating system/version

Windows 10

### Describe the bug

I want to have the labels for highlight and search be case insensitive, I tried adding '\c' to the highlight search pattern and for rg I tried adding --ignore-case to the arguments list. For the highlight, it didn't seem to work and telescope extentions breaks aswell. Even when just using `pattern = [[\b(KEYWORDS)\b]], -- match without the extra colon. You'll likely get false positives`

If there's no way I guess I have to put it in manually as alts.

### Steps To Reproduce

Adding '\c' to the highlight search pattern and for rg adding --ignore-case to the arguments list.

### Expected Behavior

It should ignore the case.

**Comment by marcaddeo** [comment]
Also interested in being able to have case insensitivity
