### ISSUE TITLE
Packer config callback doesn't seem to work?

### ISSUE THREAD

**Issue by benjie** [folke/todo-comments.nvim#178]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev git202301120020-a37c686d2-333b5866f

### Operating system/version

Ubuntu 20.04

### Describe the bug

It seems that the packer config callback doesn't allow you to register custom keywords - I'm not sure it's even being called at all.

### Steps To Reproduce

I'm using a Neovim config based off of [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim).

I wanted to add a custom keyword, so I changed the config:

```lua
  use {
    "folke/todo-comments.nvim",
    requires = "nvim-lua/plenary.nvim",
    config = function()
      require("todo-comments").setup {
        keywords = {
          ENHANCE = { icon = " ", color = "hint", alt = { "ENHANCEMENT", "IMPROVEMENT", "IMPROVE" } }
        }
      }
    end
  }
```

However, my keyword would not show up. I even tried setting `merge_keywords = false` so that ONLY my keyword was used, but still no change.

If I move the `require("todo-comments").setup` block to the bottom of my `init.lua` (i.e. outside of the `use.config()` callback) then the issue goes away, and suddenly my new keyword works.

### Expected Behavior

The packer configuration shown in the README should allow for customization.

### Repro

```Lua
-- I'm really sorry, but this seems to be an issue with `packer`/todo-comments integration
-- rather than `lazy` so I've used a different repro.lua (a very cut down version of kickstart):

-- Install packer
local install_path = vim.fn.stdpath 'data' .. '/site/pack/packer/start/packer.nvim'
local is_bootstrap = false
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  is_bootstrap = true
  vim.fn.system { 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path }
  vim.cmd [[packadd packer.nvim]]
end

require('packer').startup(function(use)
  use {
    "folke/todo-comments.nvim",
    requires = "nvim-lua/plenary.nvim",
    config = function()
      require("todo-comments").setup {
        keywords = {
          ENHANCE = { icon = " ", color = "hint", alt = { "ENHANCEMENT", "IMPROVEMENT", "IMPROVE" } }
        }
      }
    end
  }
  if is_bootstrap then
    require('packer').sync()
  end
end)

if is_bootstrap then
  print '=================================='
  print '    Plugins are being installed'
  print '    Wait until Packer completes,'
  print '       then restart nvim'
  print '=================================='
  return
end
```

**Comment by folke** [comment]
you probably didnt do packercompile after changing the config?

Anyway, works all perfectly fine for me with lazy.nvim

**Comment by benjie** [comment]
Spot on, `:PackerCompile` does indeed fix it. That's meant to be done [automatically by kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim/blob/32744c3f66ac9e66e4ac5cc9d181db50254c44b3/init.lua#L90) when I save the config file, but apparently it hasn't worked. I'll see if I can figure out why.

Thanks for trouble and todo-comments - I've only just started using them, but they're a delight so far!
