### ISSUE TITLE
bug: Packer installation code snippet on README does not call setup. requires it to be setup()

### ISSUE THREAD

**Issue by devriesd** [folke/todo-comments.nvim#182]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Linux

### Describe the bug

When setting up todo-comments with packer installation snippet :TOdoquickfix does not work since setup() is not called.

requires () to be added in snippet. 

thats all. Thanks

### Steps To Reproduce

copy code snippet for Packer installation. run :TodoQuickFix. Error msg appears saying setup has not been done.

### Expected Behavior

Should just work with code snippet.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
`()` is optional here. It works without the `()`, so whatever you put inside the brackets is probably wrong in your config

**Comment by devriesd** [comment]
I just wanted to use the default config. Did not think I had to include the default cpnfig in my init.lua file. But alas. Not plug and play after all from readme. Cheers

**Comment by folke** [comment]
I meant that in Lua, you do not need to add () to call a function if the argument is a table, so the code in the readme does in fact work. Maybe you didn't add the {} in you config function?

**Comment by folke** [comment]
Or you forgot to run packer compile?
