### ISSUE TITLE
bug: Not working when treesitter highlighting is on

### ISSUE THREAD

**Issue by leana8959** [folke/todo-comments.nvim#184]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

macOS 13.2.1 

### Describe the bug

TODO isn't highlighted. I have the default configuration.  
I also have a trailing `:` but that didn't change anything.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/87855546/223562419-f652ac6b-060a-4997-b3c3-0660db9eb193.png">

### Steps To Reproduce

"Not using your colorscheme" combined with "treesitter highlight enabled" would reproduce the issue. i.e., using your colorscheme would work no matter treesitter highlight is on or off.

### Expected Behavior

Having TODO highlighted.

### Repro

```Lua
-- I'm sorry that this is not using Lazy, yet my setup is using packer, I think this would be a more meaningful reproduction of the issue.

local install_path = vim.fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
local is_bootstrap = false
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
│       is_bootstrap = true
│       vim.fn.system { "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path }
│       vim.cmd "packadd packer.nvim"
end

require "packer".startup(function(use)
│       │
│       use "wbthomason/packer.nvim"
│       use "folke/tokyonight.nvim"
│       use "folke/todo-comments.nvim"
│       use { 'nvim-treesitter/nvim-treesitter',
│       │       run = function()
│       │       │       local ts_update = require('nvim-treesitter.install').update({ with_sync = true })
│       │       │       ts_update()
│       │       end,
│       }
│       │
│       if is_bootstrap then
│       │       require "packer".sync()
│       end
end)

vim.cmd.colorscheme("tokyonight") -- Turning off your color scheme would also stop todo-comments.nvim from working. 

require'nvim-treesitter.configs'.setup {
│ ensure_installed = {"lua"},
│ highlight = {
│   enable = true, -- Turning this on would stop todo-comments.nvim from working
│ },
}

require "todo-comments".setup()

-- TODO: This is a test
-- FIXME: This is another test
-- HACK: foobar
```

**Comment by folke** [comment]
You can use `:Inspect` to check why your colorscheme is overriding the hl groups.

**Comment by leana8959** [comment]
I just installed nvim nightly and used the inspect command.  
It gave
```
Treesitter
  - @comment.lua links to Comment lua
  - @spell.lua links to @spell lua

Extmarks
  - TodoBgTODO todo-comments
```
with or without your colorscheme enabled.

What should I try now? Thank you!

**Comment by folke** [comment]
The hl group is there, what does `:hi TodoBgTODO` say?

**Comment by leana8959** [comment]
It gives this output,  
`TodoBgTODO     xxx gui=bold guifg=#000000 guibg=#add8e6`,
I suspect that the plugin is actually changing the background colour, I just can't see it.

**Comment by folke** [comment]
As you can see the hl group and applied extmarks are correct, so this is another plugin or something else that's causing issues. Not a todo-comments problem.

**Comment by leana8959** [comment]
I see, thank you for the clarification. Is there a way I can see which plugins are changing the colour or causing the issue in some way?

**Comment by folke** [comment]
I have no idea. You'll have to debug yourself

**Comment by leana8959** [comment]
Sure, thank you for your time though.

**Comment by ja-monk** [comment]
@leana8959 sorry for coming back to this 2 years later, but I am currently having the same issue. Did you manage to figure out a solution?
