### ISSUE TITLE
feature: only highlight TODO's in commits authored by one person

### ISSUE THREAD

**Issue by head-gardener** [folke/todo-comments.nvim#188]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

In projects, worked on by many people, all the TODO's can become distracting. 

### Describe the solution you'd like

Line blame can be used to filter commits based on email or name. This will clarify more "crowded" files. Similar system can be used in TODO lists.

### Describe alternatives you've considered

Can't think of any.

### Additional context

Wondering if that's a welcomed feature. Would love to work on a PR if so.

**Comment by folke** [comment]
That's out of scope for this plugin
