### ISSUE TITLE
error scrolling in tsx file

### ISSUE THREAD

**Issue by petertriho** [folke/todo-comments.nvim#19]
For some reason this is only happening in tsx files for me. Issue goes away when I remove the plugin

```
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua Vim:E866: (NFA regexp) Misplaced {
```

**Comment by folke** [comment]
I know what's happening here, but I'm not at home right now. You can disable the comments_only option for now to prevent the error

**Comment by petertriho** [comment]
Yep! That did it. Thanks

**Comment by folke** [comment]
This should be fixed now.

**Comment by petertriho** [comment]
That was quick. Just tried it and issue has been resolved 👍
