### ISSUE TITLE
bug: Keywords aren't found

### ISSUE THREAD

**Issue by ToxyFlog1627** [folke/todo-comments.nvim#194]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Linux Gentoo

### Describe the bug

I have something like that in the file (_I already know about semicolons - I have them, that's not the issue_) :
```
// WARN: text
// PERF: text
// TEST: text
// TODO: text
```

Even though they highlight, they **aren't showing up** in any of the commands (TodoTelescope, TodoTrouble, TodoQuickFix, TodoLocList).
I **have** ripgrep installed and working and telescope also works with other plugins.

Also, maybe this will help somehow - changing colors in config doesn't have any effect.

### Steps To Reproduce

Default config with todo-comments installed using Packer.

### Expected Behavior

Keywords showing up in TodoTelescope, TodoTrouble, TodoQuickFix, TodoLocList.

**Comment by georgejean** [comment]
Have you saved your file?

**Comment by ToxyFlog1627** [comment]
Well, it's been a long time since I've last tried/tested, though AFAIK it was a folder with a few files without any ignores and without git repo

**Comment by georgejean** [comment]
Ok.
I think another common pitfall comes when we edit with TODOS a config file (in hidden folder `.config`) from outside `.config`. In this case, we don't find TODOS unless we put `--hidden` arg in plugin Spec :
```nvim
opts = {
    search = {
      args = {
        "--color=never",
        "--no-heading",
        "--with-filename",
        "--line-number",
        "--column",
	"--hidden",  -- new arg
      },
    },
    }
```
More generally, use "--hidden" to search through hidden folders or files.
