### ISSUE TITLE
bug: Custom format of TODOs

### ISSUE THREAD

**Issue by bigdavedev** [folke/todo-comments.nvim#195]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0~ubuntu1+git202304122019-23e9d625c-9b397864c-bbbf5d237~ubuntu20.04.1

### Operating system/version

Ubuntu 20.04.6 LTS

### Describe the bug

I am trying to configure the regex for the search pattern to pickup how we are supposed to write `TODO` in our repo. Valid `TODO`s are typically in the form of `TODO(ABC-123): message` where `ABC-123` is an issue in our issue handling system. This is to provide traceability for the technical debt (we have compliance processes).

I have written some regex to be able to grep these patterns, but I cannot get it to work with this plugin. Below is a screenshot showing the configuration plus the result of the plugin:
![image](https://user-images.githubusercontent.com/1699627/231711308-b8243d9c-93ab-4b5d-b676-d472c8de5f91.png)

Running this `lua` file through `ripgrep` shows that the regex is correct:
```shell
rg --color=never --no-heading --with-filename --line-number --column "\b(TODO)(\([-[:alnum:]]+\))?:" lua/plugins/todo_comments/init.lua
lua/plugins/todo_comments/init.lua:3:4:-- TODO: foo
lua/plugins/todo_comments/init.lua:4:4:-- TODO(Dave): foo
lua/plugins/todo_comments/init.lua:5:4:-- TODO(ABC-123): foo
```
How am I supposed to write the regex in the configuration?

Working regex can be seen here https://regex101.com/r/UjhTkd/1.

Please note that this issue does not concern highlighting.

### Steps To Reproduce

Using the attached `repro.lua` file:
1. `nvim -u repro.lua repro.lua`
2. Invoke `:TodoLocList`
3. Only one of the three `TODO`s is listed

### Expected Behavior

Given a set of TODOs with formats mentioned above and with the regex in the description, I expect all TODOs to be listed in the location list.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "nvim-lua/plenary.nvim",
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

require("todo-comments").setup({
  search = {
    pattern = [[\b(KEYWORDS)(\(\[-\[:alnum:\]\]+\))?:]]
  }
})

-- TODO: message
-- TODO(Dave): message
-- TODO(ABC-123): message
```

**Comment by willeccles** [comment]
I believe your issue is that `\b` in vim's regex engine matches backspace, not a word boundary. You're looking for `\<`. See `:h /character-classes` and `:h pattern-atoms` for details.

**Comment by willeccles** [comment]
Additionally, `\(` and `\)` do the opposite of what you're expecting--you want `\((...)\)` instead of `(\(...\))` here.

**Comment by willeccles** [comment]
I believe your corrected pattern should be `\<\(KEYWORDS\)\(([-[:alnum:]]\+)\)\?:` (you'll need to escape the brackets or use a different lua string syntax, but I've omitted that for clarity). Note the escaped `\+` as well.

**Comment by willeccles** [comment]
Oh, and I think you'll need to escape the backslashes in the string, i.e. `\\` instead of `\`, except when escaping brackets for the string.

**Comment by bigdavedev** [comment]
Thanks for your suggestions. This may help with the highlighting part which uses vimregex, but the search uses `ripgrep`. It is nice that the plugin uses raw string literals however; makes for fewer obscure escapes :)

**Comment by willeccles** [comment]
If the search is using rg, then the only thing you should have to change here is changing `[-[:alnum:\]\]` to `[[:alnum:]-]`. You can't escape a `]]` in a lua bracketed string, so you have to instead just never have `]]` appear in your string.

**Comment by bigdavedev** [comment]
Here is how it looks with the corrected regex for rg:
![image](https://user-images.githubusercontent.com/1699627/232077001-141efbf8-7719-45fb-a6c5-7a17f96fdfa1.png)

I also tried expanding the `[:alnum:]` part to `a-zA-Z0-9` to ensure that there was no mischief going on with the strings in Lua...

**Comment by willeccles** [comment]
Huh, you got me there. I'm out of ideas.

**Comment by bigdavedev** [comment]
> Huh, you got me there. I'm out of ideas.

:cry:

Thanks anyway for your help. If nothing else I learned about some new help pages that will come in handy :)

**Comment by bigdavedev** [comment]
This works on my Arch machine:

```
systemctl --version:  systemd 253 (253.1-3-arch)
uname -r:                 6.2.8-arch1-1
ripgrep --version:     13.0.0
```

I'll try a different version of ripgrep on my Ubuntu machine when I'm back at work tomorrow. But this isn't an issue with this plugin so this issue can be closed. Thanks @willeccles for your help.
