### ISSUE TITLE
feature: api for fetching todo counts

### ISSUE THREAD

**Issue by crides** [folke/todo-comments.nvim#197]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

Not possible yet to have the todo counts on the statusline

### Describe the solution you'd like

some api functions are provided to fetch the type, icon, and count of todos in a buffer

### Describe alternatives you've considered

can't really think of other good alternatives now; relying on loclist/telescope intermediate commands seems pretty janky

**Comment by dasupradyumna** [comment]
Although an API for this explicit purpose is missing, you can still write your own statusline component generating function using `require('todo-comments.search').search()`, as mentioned in #172.
As @folke has mentioned in that same thread, you need to properly throttle this function so it does not slow down the UI.

I have written a primitive implementation for the same purpose, but never got around to throttling it for performance since it is working well enough for me (for now). You can adapt it for your case if you wish, I will update it for throttling when I find the time.
You can find the function `statusline_todo_list()` [here](https://github.com/dasupradyumna/nvim/blob/main/lua/user/status.lua) (on line 94 at time of writing).

**Comment by crides** [comment]
Thanks. I'll look into this when I got more time

**Comment by juiceDeLemon** [comment]
> Although an API for this explicit purpose is missing, you can still write your own statusline component generating function using `require('todo-comments.search').search()`, as mentioned in #172. As @folke has mentioned in that same thread, you need to properly throttle this function so it does not slow down the UI.
> 
> I have written a primitive implementation for the same purpose, but never got around to throttling it for performance since it is working well enough for me (for now). You can adapt it for your case if you wish, I will update it for throttling when I find the time. You can find the function `statusline_todo_list()` [here](https://github.com/dasupradyumna/nvim/blob/main/lua/user/status.lua) (on line 92 at time of writing).

Hi. I'm interested in that function and the link does not work. Would you mind if you can share the function?

**Comment by dasupradyumna** [comment]
Sorry about that, here you go! :)

```lua
local todo = {
  ---@type table<string,string> map of TODO keywords and their icons
  render = {
    FIX = '',
    HACK = '',
    NOTE = '',
    PERF = '',
    TEST = '✎',
    TODO = '',
    WARN = '',
  },
  ---@type table<string, integer> map of TODO keywords and their counts
  stats = {},
}
---returns a highlight-supported string of TODO comment statistics
-- PERF: expensive function, proper throttling required
-- [ Check https://github.com/folke/todo-comments.nvim/issues/172#issuecomment-1382691260 ]
function status.statusline_todo_list()
  if not require('todo-comments.config').loaded then return '' end

  -- count number of keyword occurences
  require('todo-comments.search').search(function(entries)
    todo.stats = {}
    for _, entry in ipairs(entries) do
      todo.stats[entry.tag] = (todo.stats[entry.tag] or 0) + 1
    end
  end, { disable_not_found_warnings = true })

  local out = {}
  for keyword, count in vim.spairs(todo.stats) do
    table.insert(out, ('%%#TodoFg%s#%s %d '):format(keyword, todo.render[keyword], count))
  end
  if not vim.tbl_isempty(out) then
    table.insert(out, 1, '%#TabLineSel#◤◢%* ')
    table.insert(out, '%#TabLineSel#◤◢%*')
  end
  return table.concat(out)
end
```

There are a bunch of config-specific things here and there, but you should be able to adapt it to your tastes.

**Comment by juiceDeLemon** [comment]
thanks!

**Comment by Lazerbeak12345** [comment]
I would like this feature.
