### ISSUE TITLE
feature: custom font color instead backgound colors

### ISSUE THREAD

**Issue by MichaelC001** [folke/todo-comments.nvim#198]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

I use the transparent background in Neovim, so the default background color highlight is not working. but if I could change the font color from default black to red or something, it could still be helpful for me. thank you

### Describe the solution you'd like

custom font color

### Describe alternatives you've considered

--

**Comment by b0ae989c** [comment]
Set option `highlight.keyword = 'fg'`. Should close.

**Comment by ChristinWhite** [comment]
Like this? Can't speak for the op but unless I'm missing something that sets the background color, not the foreground text itself.

![CleanShot 2024-06-19 at 15 11 33@2x](https://github.com/folke/todo-comments.nvim/assets/1746405/71a6103f-e3c3-45c9-bd8b-5abe76011fbd)

**Comment by b0ae989c** [comment]
No. It's the option `highlight.keyword` as in
```lua
{
  "folke/todo-comments.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  opts = {
    highlight = {
      keyword = 'fg',
    },
  },
}
```

**Comment by ChristinWhite** [comment]
Interesting, not quite was I was personally hoping for but that's another nice option. Thank you!
