### ISSUE TITLE
issue launching with vimscript init

### ISSUE THREAD

**Issue by AlanWarren** [folke/todo-comments.nvim#2]
Awesome plugin! Appreciate it.  

I'm giving it a try, but having an issue using vim Plug with a vimscript init file. 

If I place the recommended / default lua snippet you've provided to call setup in my init.vim I get the following error.  

```
Error detected while processing VimEnter Autocommands for "*":  
E5108: Error executing lua .../plugged/todo-comments.nvim/lua/todo-comments/config.lua:123: attempt to concatenate local 'fg' (a nil value)
```

I expected the defaults to apply, etc. 
any ideas?

**Comment by folke** [comment]
Fixed now. This happened for colorschemes that don't set a background and/or foreground for the `Normal` highlight group.

Can you check if it's ok now?

**Comment by ahmedelgabri** [comment]
I had the same issue & now it works fine after the fix you pushed.

**Comment by danielnehrig** [comment]
ok im getting
Todo: ripgrep failed with code 1
though i have ripgrep installed

**Comment by AlanWarren** [comment]
Thanks!  I'm closing this as the issue above is resolved.  @danielnehrig  you may want to open a separate issue.
