### ISSUE TITLE
Alt for TODO has not effect

### ISSUE THREAD

**Issue by JoseConseco** [folke/todo-comments.nvim#20]
Can someone confirm that 

```lua
TODO = { icon = " ", color = "info", alt = {"TODO", "WIP","DONE"} },
```
Alt  property  - does not works - it wont highlight - additional keywords ...
![image](https://user-images.githubusercontent.com/13521338/118396819-88e13980-b651-11eb-9c25-0c161ea99b01.png)

**Comment by folke** [comment]
This should work:

```lua
require("todo-comments").setup({ keywords = { TODO = { icon = " ", color = "info", alt = { "TODO", "WIP", "DONE" } } } } ) 
```

I also just pushed a change so that keywords are also deepcopied using the defaults.

**Comment by folke** [comment]
If you're using Packer, and if you made those changes in your plugins.lua, then make sure to exit vim, open vim again, run `PackerCompile`, restart vim, to apply the changes

**Comment by JoseConseco** [comment]
Ok I tried this setup:

```lua
	use { "folke/todo-comments.nvim",
		config = function()
    require("todo-comments").setup {
			 TODO = { icon = " ", color = "info", alt = {"TODO", "WIP","DONE"} },
    }
  end
	}  
```
Restart compile, restart - no change. Maybe somebody else can confirm if they can reproduce this problem on theirs side.

**Comment by folke** [comment]
You didn't add the keywords= part?

**Comment by JoseConseco** [comment]
Ah, my bad. Sorry for wasting your time. Thanks for another great plug btw
