### ISSUE TITLE
feature: Themeing Todo Telescope

### ISSUE THREAD

**Issue by MarcCoquand** [folke/todo-comments.nvim#201]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

It is possible to theme Telescope (https://github.com/nvim-telescope/telescope.nvim#themes). However, due to the way you call telescope in todo-comments, it's hard to theme it in todos.

### Describe the solution you'd like

It'd be awesome to be able to theme the telescope. Ideally, todo-comments should use the same extension system as other systems, making themeing trivial.

### Describe alternatives you've considered

N/A

**Comment by RAprogramm** [comment]
```vim
:TodoTelescope theme=ivy initial_mode=normal previewer=false layout_config={bottom_pane={height=12}}
```
