### ISSUE TITLE
bug: setting `merge_keywords` to false breaks `TodoTelescope`

### ISSUE THREAD

**Issue by j-barnak** [folke/todo-comments.nvim#202]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

If you set `merge_keywords` to false, it breaks the command `TodoTelescope`. I was trying to only include
`FIXME`s in the highlights and Telescope, but I get presented with an error

Here's the configuration.

### Steps To Reproduce

1. Omit Keywords and only include a subset
2. Run `:TodoTelescope`

### Expected Behavior

I expect the Telescope results to only show `FIXME`s

### Repro

```Lua
return {
  "folke/todo-comments.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
  },
  cmd = { "TodoTelescope" },
  event = { "BufReadPost", "BufNewFile" },
  config = true,
  opts = {
    signs = false,
    keywords = {
      FIX = {
        color = "#56B6C2",
        alt = { "FIXME", "BUG", "FIXIT", "ISSUE" },
      },
    },
    merge_keywords = false,
  },
  keys = {
    { "<leader>ft", "<cmd>TodoTelescope<cr>", desc = "Todo" },
  },
}
```

**Comment by dandyrow** [comment]
I have found this bug too. I thought there was something wrong as I installed the plugin but it wasn't working with Telescope. Disabled merge_keywords and it started working

**Comment by b0ae989c** [comment]
This more of a missing config issue. You need to provided `icon` when you set `merge_keywords = false`. Otherwise Telescope entry maker will fail.
