### ISSUE TITLE
bug: Using lazy.vim, failing to specify opts or config = true doesn't work

### ISSUE THREAD

**Issue by ngryman** [folke/todo-comments.nvim#209]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 12.6.5

### Describe the bug

If you don't explicitly specify `opts` or `config = true` when loading the plugin with `lazy.vim`, the plugin is marked as loaded by `lazy.vim` but commands and highlighting don't work.

My understanding is that `opts` or `config` are optional, so the following should work:
```lua
{
    "folke/todo-comments.nvim",
    ft = { "css", "html", "lua", "rust", "typescript" },
    dependencies = { "nvim-lua/plenary.nvim" },
},
```

### Steps To Reproduce

1. Add the following to your `lazy.vim` configuration (or use the `repro.lua` below):

```lua
{
    "folke/todo-comments.nvim",
    lazy = false,
    dependencies = { "nvim-lua/plenary.nvim" },
},
```

2. Restart NeoVim
3. Execute `:Lazy`
4. The plugin should be marked as loaded
5. Execute `:TodoQuickFix`
6. The following message is displayed: "todo-comments isn't loaded. Did you run setup()?"

### Expected Behavior

It should display the quick fix pane.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
What makes you think `opts` is optional?

It's literally in the docs. add `opts={}`

**Comment by ngryman** [comment]
[Lazy.vim manual](https://github.com/folke/lazy.nvim#-installation):
![](https://cdn.zappy.app/70cb2f9562e6362845b421bdad765ed9.png)

Other plugins respect that. Also your `repro.lua` literally doesn't work OOB because of that.

**Comment by folke** [comment]
Yes, but this plugin does require setup. See the readme

**Comment by folke** [comment]
You even got an error that literally indicates you have to run setup, or use `opts=...` in the lazy case

**Comment by ngryman** [comment]
> Yes, but this plugin does require setup. See the readme

I've read the readme. My issue is not with the docs. My issue is with DX and the fact that it contradicts the `fuzy.nvim`'s readme and the way other plugins work. It is confusing why `opts` has to be explicitly specified to an empty value. Is there a technical reason for that? Is it difficult to fall back to the defaults when omitted?

> You even got an error that literally indicates you have to run setup, or use opts=... in the lazy case

It doesn't specify `or use opts=...`. I have: `todo-comments isn't loaded. Did you run setup()?`

---

On a side note, it would be nice to not assume people don't read the docs. Perhaps there is indeed something confusing about the docs themselves or the API. All of this seems pretty obvious to you, but it's not for every one of your users.

**Comment by folke** [comment]
What are you even talking about?

The screenshot you posted is for the options for lazy.nvim.

```lua
require("lazy").setup(plugins, opts)
```

That;s not even related to a plugin spec's `opts=...`.

That has nothing todo with setting up this plugin.

When you add `config=true`, or `opts={...}`, then lazy knows that this is a plugin where lazy needs to call `require("the_plugin").setup(the_opts)`

Not all plugins require `setup`. So if you don't specify `opts` or `config=true` in a lazy spec, then it's setup function will not be called.

So again, this has all nothing todo with the `todo-comments` plugin.
