### ISSUE TITLE
Add option to search for "todo-comments" in specific folder / current buffer

### ISSUE THREAD

**Issue by alexander-born** [folke/todo-comments.nvim#21]
Great plugin! 

Can you add a option to limit the search of "todo-comments" in a specific folder/ current buffer for `TodoQuickFix` and `TodoTrouble` and `TodoTelescope`? 

In huge projects the resulting list has too many entries to be usable. It takes quite a while as well.

**Comment by folke** [comment]
Great idea! I'll add it soon

**Comment by folke** [comment]
Just added this. See the docs about the commands on how to use it.

Make sure to update `trouble` as well to make it work there.

Thank you for the suggestion!
