### ISSUE TITLE
bug: plugin is making the intro disappear when opening neovim

### ISSUE THREAD

**Issue by aldevv** [folke/todo-comments.nvim#210]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu LTS

### Describe the bug

intro disappears right after opening neovim  

### Steps To Reproduce

1.open neovim with no file

### Expected Behavior

1. the intro message should appears (the one that appears with the :intro command)

**Comment by folke** [comment]
Just defer loading todo comments till `VimEnter` or a similar event.
todo comments, creates hl groups and that causes a redraw, making the intro disappear
