### ISSUE TITLE
bug: TodoTrouble is the only picker that shows TODOs from other files in the project?

### ISSUE THREAD

**Issue by GideonWolfe** [folke/todo-comments.nvim#218]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Arch Linux

### Describe the bug

When I open the view with `:TodoTrouble`, I can see many different TODOs from across files in this project 

![image](https://github.com/folke/todo-comments.nvim/assets/32942052/ba6a306c-f2a6-4cf4-bc05-41f5a3e56f5c)

However if I use any of the other pickers, for example `:TodoLocList`, I only see TODOs from the current file

![image](https://github.com/folke/todo-comments.nvim/assets/32942052/2aa14c10-496b-4f6f-b87a-1d02f62b63ff)

### Steps To Reproduce

1. Open TodoTrouble and observe multiple files
2. Open other picker and see only file currently open

### Expected Behavior

All pickers should show TODO items across entire project

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by drusmanbashir** [comment]
May I add that seeing current file to do is desirable in some instances? Can an option be added so that we can configure todo list from file only versus entire project?

**Comment by b0ae989c** [comment]
This doesn't look like a bug. Your repro config does not install `trouble`. Could you provide the proper repro so I can investigate this issue?

**Comment by drusmanbashir** [comment]
Hi @b0ae989c  if that question was for me, then no its a feature enhancement request. I have opened a separate ticket today for it.
