### ISSUE TITLE
Doesn't work on .svelte file

### ISSUE THREAD

**Issue by kiuKisas** [folke/todo-comments.nvim#22]

**Comment by folke** [comment]
Probably the comment parsing. Does it work with only_comments = false?

**Comment by folke** [comment]
I changed the implemention that checks wether a keyword is in a comment by using treesitter instead of commenstring.

Let me know if you have any more issues!

**Comment by kiuKisas** [comment]
Just update and here is the result:
![image](https://user-images.githubusercontent.com/12698940/118614353-eeebcf00-b7bf-11eb-879f-93b07fd15233.png)

**Comment by folke** [comment]
Should be fixed now. I didn't check **all** treesitter language trees.

It should now properly highlight in any comment (for any language that supports treesitter)

![image](https://user-images.githubusercontent.com/292349/118621853-9e528280-b77b-11eb-9381-099496a770b5.png)

**Comment by kiuKisas** [comment]
I confirm it work ! Thank's for your hard work :)
