### ISSUE TITLE
Alternative keyword as symbol?

### ISSUE THREAD

**Issue by OSITO326** [folke/todo-comments.nvim#225]
I hope you can help me, I was trying to add two new keywords with their alternative but the alternative is a symbol
but don't catch the alternatives when I call them ` []: ` or ` [X]: `
I have the configuration like this:
```lua
keywords = {
  TODO = { icon = "󱓵 ", color = "info" },
  DO = { icon = "", color = "info", alt = { "[]" } },
  DONE = { icon = "", color = "info", alt = { "[X]" } },
},
highlight = {
  pattern = [=[.*<(KEYWORDS)(\([^)]*\))?:|\[%s*%]|%[X%]]=],
},
```
The case is that not if I'm failing in the `pattern = {}`. Maybe you could give me a hand with `search = {}` 🙏

Thanks in advance! 😅

**Comment by b0ae989c** [comment]
Duplicate of #213. Should close.
