### ISSUE TITLE
Scrolling in binary files results in error

### ISSUE THREAD

**Issue by crides** [folke/todo-comments.nvim#23]
When opening binary files I get this:

```
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua Vim:E731: using Dictionary as a String
```

Using the master as of now.

**Comment by folke** [comment]
This was a weird one. I double checked and while I'm definitely passing two strings to `matchlist` (checked to be sure with `type(...)`, Vim gives that error. Probably because the string contains binary data.

Just pushed a fix to prevent that error. Thank you for reporting.

**Comment by crides** [comment]
Thanks! The issue seems to be fixed for me.
