### ISSUE TITLE
feature: add option to not install commands by default

### ISSUE THREAD

**Issue by BerkeleyTrue** [folke/todo-comments.nvim#235]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

I like having fine grain control of commands list.

### Describe the solution you'd like

I'd like to remove the default commands, which are provided by plugins/todo.vim. 

### Describe alternatives you've considered

Not using todo-comment? Not sure what to put here but github won't let me submit unless I put something here...

### Additional context

I can provide a PR that would add a vim option that is checked before adding commands, so others can disable built in commands.

**Comment by folke** [comment]
Sorry, but no
