### ISSUE TITLE
bug: No signs at signcolumn

### ISSUE THREAD

**Issue by Parsifa1** [folke/todo-comments.nvim#240]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev-1611+g48803858093

### Operating system/version

5.15.123.1-microsoft-standard-WSL2

### Describe the bug

with all default settings,there are no signs at signcolumn

### Steps To Reproduce

![image](https://github.com/folke/todo-comments.nvim/assets/31800073/637728b3-c808-4607-bc68-2455aee494b2)

only set signs = true

### Expected Behavior

![image](https://github.com/folke/todo-comments.nvim/assets/31800073/f8edce90-1188-4a14-8125-4645ebfa9542)

there should be have sign at signcolumn

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

require("todo-comments").setup({
    signs = true,          -- show icons in the signs column
})
vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Parsifa1** [comment]
i forgot the : sign ,sorry : (
this is an amazing plugin

**Comment by s-aditya-dev** [comment]
what  was your issue and how did u fixed it can u tell me i facing the same issue and i cant see the signs and the text after keyword is not highlighted:
![image](https://github.com/user-attachments/assets/e2d1830e-5e26-403e-95bb-0bbe3164f352)
