### ISSUE TITLE
feature: someplace to share todo-comments configs 

### ISSUE THREAD

**Issue by elmarsto** [folke/todo-comments.nvim#242]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

I have spent a lot of time perfecting my config. In particular, the system of keywords I've developed, along with the icons, is fantastic.  I want to share it. 

### Describe the solution you'd like

Someplace (a wiki?) to share them

### Describe alternatives you've considered

Setting up e.g. awesome-todo-comments.nvim

### Additional context

Why, thank you for asking, here is my config :)

![image](https://github.com/folke/todo-comments.nvim/assets/315987/0d9de40e-2ab5-486f-94c6-0e93fb3ba75d)
https://gist.github.com/elmarsto/7ebd8e7385a7bdd6ffab151c89b17e14

**Comment by b0ae989c** [comment]
Use discussion. See https://github.com/folke/todo-comments.nvim/discussions/categories/show-and-tell. Should close.
