### ISSUE TITLE
feature: split telescope integration into a separate plugin

### ISSUE THREAD

**Issue by KirkEasterson** [folke/todo-comments.nvim#245]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

Yes, but a small problem. I like lazy-loading plugins with mappings (telescope for example). And I like loading some plugins at startup or with events (highlighting TODO comments for example).

I currently use `event = "VimEnter"` for this plugin (todo-comment.nvim) when lazy loading. This allows me to view the TODOs in the status col and have highlighting for TODOs immediately when I open a file. _But_, I also like using `TodoTelescope` to view all of the project TODOs.

With the current state of this plugin, I must have `telescope` (and its dependecies) as a dependency on the `VimEnter` event. The difference in startup-time is negligible to be honest. But this is the only plugin that prevents me from lazy-loading `telescope` with a keybinding.

To summarize the problem: this plugin has features that one may want at startup, and some that one may want lazy-loaded. But the lazy-loaded features can't be lazy loaded in an effective way.

### Describe the solution you'd like

Separate the `telescope` integration into a separate plugin (`telescope-todo-comments.nvim`) for example. This is an opinionated suggestion, but it separates concerns in a more clear way.

### Describe alternatives you've considered

I have a work-around where I add `todo-comments` as a dependency for `telescope`, and then add the binding for `:TodoTelescope` to my `telescope` config. This works, but then my config for separate plugins is tightly coupled and it makes it difficult to "turn off" plugins if I no longer wish to use them.

### Additional context

I can do the work for this new plugin since this is a specific request. It may cause some confusion in the "folke ecosystem", so it may have value if `folke` creates the repo and then I make PRs to it. But I don't feel strongly about this.

**Comment by sbeyer** [comment]
While at it, I wonder why we have `:TodoTelescope` instead of `:Telescope todo` or similar.

**Comment by folke** [comment]
`todo-comments` doesn't need telesope.nvim when you run it's setup, so you must be loading it wrong.

If you're using lazy.nvim, then you don't need to specify "telescope.nvim" as a depenency. Lua code deps are resolved automatically and lua requires are automatically lazy-loaded.
