### ISSUE TITLE
bug: no highlight in markdown

### ISSUE THREAD

**Issue by CnsMaple** [folke/todo-comments.nvim#247]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1956+gec7453804

### Operating system/version

windows11

### Describe the bug

 I have already looked at it  #150 

`markdown` and `markdown_inline` has already been installed

What should I do.

![图片](https://github.com/folke/todo-comments.nvim/assets/92523839/47b87de5-1065-4e3f-aa7d-384931313aa3)

but when i run`:TodoTelescope`:

![图片](https://github.com/folke/todo-comments.nvim/assets/92523839/4cce03cc-946e-4f21-aa25-4804166096d2)

### Steps To Reproduce

no

### Expected Behavior

highlight

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by fredrikaverpil** [comment]
@CnsMaple do you remember what you did to fix this?

I've got the same issue where `markdown` and `markdown_inline` is installed and I see the syntax highlighting in `:TodoTelescope`, but not in the buffer.

**Comment by linkarzu** [comment]
Did you guys fix it? I have the same issue. Cannot see the color in markdown files, but I do see the TODOs highligted in other files, like lua files for example

**Comment by linkarzu** [comment]
Oh, just found out why @fredrikaverpil, it has to be a comment, see:
https://github.com/folke/todo-comments.nvim/issues/150#issuecomment-1306826575
