### ISSUE TITLE
bug: highlight does not work

### ISSUE THREAD

**Issue by zaiqiang-dong** [folke/todo-comments.nvim#249]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Linux NB 5.15.0-88-generic #98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Describe the bug

highlight does not work , but icon is show.
![image](https://github.com/folke/todo-comments.nvim/assets/10396859/a52d7845-73b2-467d-9518-febdd6a9184e)

### Steps To Reproduce

![image](https://github.com/folke/todo-comments.nvim/assets/10396859/a10f5c4f-e19e-4a63-bd39-ec26b8580d2e)

### Expected Behavior

help

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by nkarl** [comment]
Seems to have stopped working after switching from Packer to Lazy.

**Comment by Sebbito** [comment]
Same thing here.
Neovim 0.9.5 with default opts and lazy as pm.

**Comment by einKnuffy** [comment]
Wrong... Just install the treesitter parser `comment`, related to https://github.com/nvim-treesitter/nvim-treesitter/issues/236#issuecomment-1058308070

**Comment by ibehnam** [comment]
@kjellherzke is right, just do `:TSInstall comment`.
