### ISSUE TITLE
Just work for "TODO", but not for "FIX", "HACK", etc

### ISSUE THREAD

**Issue by UltiRequiem** [folke/todo-comments.nvim#25]
I'm doing something wrong?

https://user-images.githubusercontent.com/71897736/118994778-3c954280-b94c-11eb-9ca9-457d7e214709.mp4

**Comment by folke** [comment]
The default pattern only matches when the keyword is followed by a colon like `HACK: fdsfsdf`.

See the [config](https://github.com/folke/todo-comments.nvim#%EF%B8%8F--configuration) section in the readme

**Comment by UltiRequiem** [comment]
Oh sorry, I really read the config...
