### ISSUE TITLE
feature: support username

### ISSUE THREAD

**Issue by cxwx** [folke/todo-comments.nvim#258]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

support `TODO(username): .....`
because some of the lint like cpplint use `TODO(username):` as feature

### Describe the solution you'd like

support `TODO(username): .....`

### Describe alternatives you've considered

no

**Comment by mhutchinson** [comment]
Looks like this is a duplicate of #10

**Comment by cxwx** [comment]
> Looks like this is a duplicate of #10

yes
