### ISSUE TITLE
bug: default neovim dashboard does not appear [LOW PRIORITY]

### ISSUE THREAD

**Issue by AXVIII3** [folke/todo-comments.nvim#261]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11

### Describe the bug

The default neovim dashboard does not appear or instantly disappears when this plugin is active

![DashboardIssue](https://github.com/folke/todo-comments.nvim/assets/76608488/ba455b9d-26f6-4542-9900-28cc1eb67fd1)

### Steps To Reproduce

1. Install and set up todo-comments
2. Default dashboard no longer appears
3. Remove todo-comments config and restart
4. Nvim default dashboard appears

### Expected Behavior

todo-comments should be set up AND nvim default dashboard should appear..

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
  {
    "folke/todo-comments.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = {}
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by fabiosouzadev** [comment]
I have a same problem.

**Comment by migueel15** [comment]
Same here

**Comment by tak5633** [comment]
I have this same problem. Issue #133 describes the offending lines, a brief description why, and a work around. The work around fixed the problem for me.

**Comment by AXVIII3** [comment]
> I have this same problem. Issue #133 describes the offending lines, a brief description why, and a work around. The work around fixed the problem for me.

Ooh.. I didn't see that issue.. should have searched for "start screen" too... Thanks will check out the solution.
Closing as duplicate
