### ISSUE TITLE
plugin doesn't seem to work

### ISSUE THREAD

**Issue by eric-marin** [folke/todo-comments.nvim#270]
### Did you check docs and existing issues?

- [x] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-3

### Operating system/version

6.9.2.arch1-1

### Describe the bug

![image](https://github.com/folke/todo-comments.nvim/assets/144999446/d77c5122-e7d2-4677-9829-751e844d8317)

I copy-pasted the installation, I have installed all the dependencies, I used the default config, I even put the colon, still doesn't want to work.
Am I missing something?

### Steps To Reproduce

.

### Expected Behavior

working plugin

**Comment by the-code-rx** [comment]
Make sure you have `opts` referenced in the plugin install; otherwise, the defaults will not be initialized. I had a similar issue with Ubuntu and that fixed my issue.

`{
  "folke/todo-comments.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  opts = {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
  }
}`

**Comment by dsaad68** [comment]
I'm experiencing the same problem.

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by chuan2984** [comment]
same here, the commands work correctly. Im assuming a highlight issue?

**Comment by danilo-alm** [comment]
Same here, on NVIM v0.10.0. When trying to run :TodoTelescope, I get:

```
Error executing Lua callback: ...omments.nvim/lua/telescope/_extensions/todo-comments.lua:26: attempt to index field 'search' (a nil value)
stack traceback:
	...omments.nvim/lua/telescope/_extensions/todo-comments.lua:26: in function <...omments.nvim/lua/telescope/_extensions/todo-comments.lua:24>
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:183: in function 'run_command'
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:259: in function 'load_command'
	...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:10
```

**Comment by JxJxxJxJ** [comment]
Same ...

**Comment by datadevda1** [comment]
I added the require to a config = function(), and things seemed to work for me using the entry below:

{
    "folke/todo-comments.nvim",
    dependencies = "nvim-lua/plenary.nvim",
    lazy = true, --optional
    event = { "BufReadPost", "BufWritePost", "BufNewFile" },
    config = function()
      require("todo-comments").setup {
        -- your configuration comes here
        -- or leave it empty to use the default settings
        -- refer to the configuration section below
      }
    end
}


![todo-comments](https://github.com/folke/todo-comments.nvim/assets/160189927/deace635-f14f-4526-84f8-ea28cf029fdc)


Let me know if this does the trick for you

**Comment by folke** [comment]
@datadevda1 that's exactly the same as `opts = {}`.
@eric-marin why do you add `lazy=true`? that's not needed.
@danilo-alm you didn't call setup, or don't have a correct lazy spec or packer or whatever you use

Closing

**Comment by danilo-alm** [comment]
@folke I'm not at my computer rn but I'm pretty sure that was the problem, sorry. That's a while without using neovim. I suggest including the setup funcion in the readme's "Lazy" section to avoid this, what do you think?

**Comment by folke** [comment]
It shows the exact spec you need in the readme.
https://github.com/folke/todo-comments.nvim?tab=readme-ov-file#-installation

**Comment by folke** [comment]
`opts = {}` in a lazy spec does **EXACTLY** the same as `require('todo-comments').setup({})`

**Comment by folke** [comment]
You do need to have `opts = {}`, even when it's empty. Otherwise setup won't be ran.

**Comment by datadevda1** [comment]
thanks @folke ! Yep, I just tried the opts = {} and everything is still working.  I'm not quite sure what the issue was when I tested the first time. Still new to Neovim.

![todo-comments_1](https://github.com/folke/todo-comments.nvim/assets/160189927/64bb33a4-22f6-4b50-a520-720ed5d7c2ed)

**Comment by danilo-alm** [comment]
> `opts = {}` in a lazy spec does **EXACTLY** the same as `require('todo-comments').setup({})`

I see. I was setting some keymaps inside my config, and it seems that an empty "opts" isn't enough in these cases. Adding the setup function worked. Thanks.

```
{
  "folke/todo-comments.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  config = function()
    vim.keymap.set("n", "]t", function()
      require("todo-comments").jump_next()
    end, { desc = "Next todo comment" })

    vim.keymap.set("n", "[t", function()
      require("todo-comments").jump_prev()
    end, { desc = "Previous todo comment" })

    require("todo-comments").setup()
  end,
}
```

**Comment by eric-marin** [comment]
@folke i just discovered that if i do :help for some reason the plugin starts working
![image](https://github.com/folke/todo-comments.nvim/assets/144999446/0122fdbe-01ab-42ce-b682-d4d514a4093e)
the command :TodoTrouble only works after i ran :TodoLocList or :TodoQuickFix.
then if i close the help.txt buffer or move the focus it stops working
