### ISSUE TITLE
bug: TodoTrouble keywords don't work with trouble v3

### ISSUE THREAD

**Issue by 0xN1nja** [folke/todo-comments.nvim#271]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Arch Linux

### Describe the bug

After you merged the dev branch of Trouble into master. I had to migrate my Trouble from v2 to v3. I noticed that when I run the `:TodoTrouble` command, the Trouble window opens:

![image](https://github.com/folke/todo-comments.nvim/assets/71812498/59feaf2f-625f-45e4-a6ed-3c1fa3467f43)

I wanted to filter TODOs with other keywords. Upon seaching, I found that we can achieve this by passing `keywords` to `TodoTrouble` to only search for specific keywords. You've also used that in LazyVim at [line 475](https://github.com/LazyVim/LazyVim/blob/b289fea1636eda08d82344dc32a114bca550e375/lua/lazyvim/plugins/editor.lua#L475).

But this is not working in Trouble v3. A screenshot of TodoTrouble after passing `keywords=TODO,FIX,FIXME`:

![image](https://github.com/folke/todo-comments.nvim/assets/71812498/569c4502-c911-4baa-8443-32c9b339bee9)

`TodoTrouble` is not able to filter TODOs with other keywords.

### Steps To Reproduce

None

### Expected Behavior

I expected TodoTrouble to filter out TODOs, FIXs and FIXMEs with other keywords when passed `keywords=TODO,FIX,FIXME`

**Comment by folke** [comment]
You can use trouble's filters for this.

Example for just todo.

`:Trouble todo filter={tag = TODO}`

**Comment by folke** [comment]
Or for multiple tags: `:Trouble todo filter={tag = {TODO, HACK}}`
