### ISSUE TITLE
bug: Highlight dissapearing after few ms

### ISSUE THREAD

**Issue by JxJxxJxJ** [folke/todo-comments.nvim#273]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: RelWithDebInfo LuaJIT 2.1.1713484068 

### Operating system/version

Linux

### Describe the bug

[Grabación de pantalla desde 2024-06-04 18-13-58.webm](https://github.com/folke/todo-comments.nvim/assets/103049321/e38416ef-e3b6-444c-bc7e-d78e03b2c83d)

### Steps To Reproduce

This in plugins table 

```lua
	"folke/todo-comments.nvim",
	dependencies = "nvim-lua/plenary.nvim",
	lazy = true, --optional
	event = { "BufReadPost", "BufWritePost", "BufNewFile" },
	config = function()
		require("todo-comments").setup {
			-- your configuration comes here
			-- or leave it empty to use the default settings
			-- refer to the configuration section below
		}
	end

```

I can also reproduce it using the Repro.lua file 
![image](https://github.com/folke/todo-comments.nvim/assets/103049321/f8eb5c1d-0982-4143-9b70-1df3220520d1)

### Expected Behavior

I'd love if the keywords were shown as the image in the repo, with bright colors and colored following text

### Repro

```Lua
-- Reproduced with this file

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by b0ae989c** [comment]
This is not a bug. `-- TODO` is not supposed to be highlighted here since the default the highlight pattern is `.*<(KEYWORDS)\s*:`. Should close.

**Comment by folke** [comment]
exactly

**Comment by JxJxxJxJ** [comment]
Ahh. How silly. Thank you!

**Comment by folke** [comment]
And just so you know, those highlights your see for a split second are not how the ones from todo-comments look like

**Comment by JxJxxJxJ** [comment]
![image](https://github.com/folke/todo-comments.nvim/assets/103049321/3d0dabb9-08af-46d7-a644-0b6942eea210)
Yeah, I've no idea where the others came from. Doing keyword: works just fine though :smile:
