### ISSUE TITLE
bug: keywords are highlighted when inside of a map in go

### ISSUE THREAD

**Issue by vague2k** [folke/todo-comments.nvim#281]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

keywords like WARN or INFO are being shown inside the Telescope picker / QuickFix List when the same keyword is being used inside of a map in golang.
<img width="636" alt="Screenshot 2024-06-22 at 1 52 29 PM" src="https://github.com/folke/todo-comments.nvim/assets/121782036/6d7aac91-7b56-42d0-b214-2086e24f9667">

### Steps To Reproduce

1. copy the following into a go file
```go
const (
	DEBUG int = iota
	INFO
	WARN
	ERROR
	FATAL
)

var LogLevelColors = map[int]string{
	DEBUG: "cyan",
	INFO:  "green",
	WARN:  "yellow",
	ERROR: "red",
	FATAL: "purple",
}
```
2. open the go file and open either `:TodoTelescope` or `:TodoQuickFix`
3. Should see keywords that are not comments be shown in either picker.

### Expected Behavior

Should expect these keywords to not show up in any picker since they are not comments.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by b0ae989c** [comment]
This is expected behavior. not a bug. The default search pattern is `[[\b(KEYWORDS):]]`, which matches the strings in your snippet.

You need to define alternative keywords, and set `merge_keywords = false`.

**Comment by vague2k** [comment]
Sure, thanks for the quick response.

Is it possible you can point me to where the search pattern is used in source?

**Comment by b0ae989c** [comment]
It's used to build search regex. See https://github.com/folke/todo-comments.nvim/blob/51e10f838e84b4756c16311d0b1ef0972c6482d2/lua/todo-comments/config.lua#L122-L124

**Comment by vague2k** [comment]
> It's used to build search regex.

Thanks again! considering this complete and will be closing the issue
