### ISSUE TITLE
feature: TodoTelescope option to ignore directories

### ISSUE THREAD

**Issue by coxley** [folke/todo-comments.nvim#287]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

Many of the projects I work in have generated code or git submodules. I'd like to check for a list of todos/fixmes/etc, but there's not currently a way to ignore certain paths.

### Describe the solution you'd like

An additional parameter to `TodoTelescope` (and the other variants) would probably do it. Being able to provide multiple directories and/or globs would be solid. 

### Describe alternatives you've considered

Some projects have relevant code under a single dir, like `proj/src` with generated stuff at `src/gen` and `src/protos`. But that's a minority. Most share a parent directory, so providing explicit search paths would be unique per project.

**Comment by b0ae989c** [comment]
We don't need a new feature for this. Add those generated directories to `.ignore` and telescope will skip them. Should close.

**Comment by coxley** [comment]
@b0ae989c: I see... it does seem to acknowledge `.gitignore` but I'm seeing more results than I'd expect from submodules still. Those can't be ignored, for obvious reasons.

**Comment by b0ae989c** [comment]
`.ignore` and `.gitignore` are two different files.

Directories in `.ignore` are not skipped for Git, but they are skipped for Telescope's fuzzy searcher.
