### ISSUE TITLE
Something weird is going on? todo-comments is activating nvim-tree?

### ISSUE THREAD

**Issue by qazip** [folke/todo-comments.nvim#3]
So, I have just added the Plug line, and a keymap:

`nnoremap <silent><C-t> <cmd>TodoTelescope<CR>`

Now, whenever I do "C-t", I do get TodoTelescope. However, while telescope is opened, do C-t again and for some reason, nvimtree (sidebar) is activated. Now, do "C-t" again and telescope dissapears, but sidebar remains. Weird thing comes now: do ":q" over and over and it won't quit, it will just close and re-open the file. Yep, ":q" re-opens the file.

How should I go about debugging this?

**Comment by folke** [comment]
<c-t> is probably an action mapping in Telescope too?

`TodoTelescope` simply does `:Telescope todo-comments todo`

**Comment by folke** [comment]
Or do you mean the `trouble` plugin instead of `nvimtree`?

**Comment by qazip** [comment]
Ah yes, apparently, nvim-tree has a default bind for C-t:

`      ["<C-t>"]          = tree_cb("tabnew"),`

How do I clear a keybind?

**Comment by folke** [comment]
`:unmap <C-t>`?

Anyway, this doesn't seem to be related to `todo-comments` right?

**Comment by qazip** [comment]
Ya, seems like not. Sorry!

**Comment by qazip** [comment]
Hey @folke, sorry for the bother.

What do you get when you do :TodoTelescope and then, while it is opened and an entry selected, do :TodoTelescope (you need a key for this)? I just disabled some plugins and am still getting weird behaviour.

**Comment by qazip** [comment]
Apparently, C-t is also mapped in telescope. I tried disabling it but I am having no luck whatsoever. Do I perhaps have to disable the default telescope keybinds on todo-comments side as well? What a headache...
