### ISSUE TITLE
Add support for Doxygen todos

### ISSUE THREAD

**Issue by ranebrown** [folke/todo-comments.nvim#30]
Would it be possible to add support for Doxygen style todos: `\todo` or `@todo`? Instead of matching `:` as the last character match the first character (while also keeping default behavior). Thanks!

https://www.doxygen.nl/manual/commands.html#cmdtodo

**Comment by folke** [comment]
You should be able to tweak the regex to do exactly that. I'm not home right now, but if you need help with the regex I can have a look tomorrow

**Comment by ranebrown** [comment]
I got a chance to try adjusting the regex but couldn't quite get it working. I think it might be related to needing to adjust both the `rg` regex and the vim highlight regex.

I got results with rg using `@*\b(todo|TODO)(\s|:)` and search matches within vim using`\v\C(.*\@*<(todo|TODO)(\s*|:))`.

todo-comments patterns:
```lua
    keywords = {
        FIX = {
            icon = " ", -- icon used for the sign, and in search results
            color = "error", -- can be a hex color, or a named color (see below)
            alt = {"FIXME", "BUG", "FIXIT", "FIX", "ISSUE"} -- a set of other keywords that all map to this FIX keywords
            -- signs = false, -- configure signs for some keywords individually
        },
        TODO = {icon = " ", color = "info", alt = {"todo"}},
        todo = {icon = " ", color = "info"},
        HACK = {icon = " ", color = "warning"},
        WARN = {icon = " ", color = "warning", alt = {"WARNING", "XXX"}},
        warning = {icon = " ", color = "warning"},
        PERF = {icon = " ", alt = {"OPTIM", "PERFORMANCE", "OPTIMIZE"}},
        NOTE = {icon = " ", color = "hint", alt = {"INFO"}}
    },
    highlight = {
        before = "", -- "fg" or "bg" or empty
        keyword = "wide", -- "fg", "bg", "wide" or empty. (wide is the same as bg, but will also highlight surrounding characters)
        after = "fg", -- "fg" or "bg" or empty
        pattern = [[(.*\@*<(KEYWORDS)(\s*|:))]], -- pattern used for highlightng (vim regex)
        comments_only = true -- uses treesitter to match keywords in comments only
    },
    search = {
        command = "rg",
        args = {
            "--color=never", "--no-heading", "--with-filename", "--line-number",
            "--column"
        },
        pattern = [[@*\b(KEYWORDS)(\s|:)]] -- ripgrep regex
    }
```

Using this for testing.
```c
/**
 * @brief test
 * @todo do this
 * @note this is a note
 * @warning this is a warning
 * TODO: normal todo
 * WARNING: normal warning
 */
```

Any ideas?

**Comment by ranebrown** [comment]
I think this is the pattern to use but the index of results from [matchstr](https://github.com/folke/todo-comments.nvim/blob/8560546c466d1f555573d37e062e95e7ae94bbab/lua/todo-comments/highlight.lua#L18) in `highlight.lua` seems to be off since there are some empty entries.

```lua
highlight = {
    pattern = [[.*[@\\]{1}<(KEYWORDS)\s*|.*<(KEYWORDS)\s*:]],
},
search = {
    pattern = [[[\\\\@]*\b(KEYWORDS)(\s|:)]],
}
```

**Comment by caschbre** [comment]
@ranebrown Did you ever get this working?  I've tried those patterns and they don't seem to match / highlight all of your testing examples.

**Comment by ranebrown** [comment]
Yes it works for me. You might also need to update the keywords section in the config to match the lowercase strings if you haven't done that. E.g. `TODO = { icon = " ", color = "info", alt = { "todo" } },`
