### ISSUE TITLE
bug: regex capturing groups not working as they were in version 1.2.0

### ISSUE THREAD

**Issue by fvall** [folke/todo-comments.nvim#302]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Linux/PopOs

### Describe the bug

Using the recommended options in the README file, I have amended the regex patters to suit my workflow. They were working just fine when I tested it with version 1.2.0. I have recently updated to v.1.3.0 and the highlight behaviour has changed, even though the regex patterns did not.

After playing a bit with the configuration, it seems to me the regex capturing groups are not working as they were previously. In my custom regex, I add a modifier to the capturing group, and I think that is causing the issue.

### Steps To Reproduce

Switch between versions 1.2.0 and the latest one (as of writing it is 1.3.0) and check the Todo comments in the script below.

With version 1.2.0
- both todos are highlighted
- both can be found with `TodoQuickFix`
- both can be found with `TodoTelescope`.

With version 1.3.0
- the first one is not found
- both are found with `TodoQuickFix`
- neither are found with `TodoTelescope`

### Expected Behavior

I am not sure whether this is now the expected behaviour after version 1.3.0 or if it is indeed a bug. I read the release notes and I saw some comments about changing some of the regex logic. I also tried to change my regex to see if would resolve the issue, but it did not work either.

### Repro

```lua
local plug = {
  {
    "folke/todo-comments.nvim",
    name = "todo_comments",
    lazy = false,
    tag = "v1.2.0",  -- fixing version, remove here to cause the issue
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    opts = {
      highlight = {
        before = "",
        keyword = "bg",
        after = "fg",



        
        -- ===================================
        --   This is my custom regex pattern
        -- ===================================
        pattern = [[.*<(KEYWORDS)\s?(\(\a*\))?\s*:]], -- pattern or table of patterns, used for highlighting (vim regex)



      },
      search = {
        command = "rg",
        args = {
          "--color=never",
          "--no-heading",
          "--with-filename",
          "--line-number",
          "--column",
        },


        -- ===================================
        --   This is my custom regex pattern
        -- ===================================
        pattern = [[\b(KEYWORDS)\s?(\(\w*\))?\s*:]], -- ripgrep regex



        
        
      },
}

  },
}

-- TODO(fvall): this a named todo
-- TODO: This is a normal todo
vim.keymap.set("n", "<leader>fd", "<cmd>TodoTelescope<cr>", {desc = "Find todo"})
return plug
```

**Comment by wuxiao889** [comment]
meet this too
pattern = [[\b(KEYWORDS)\(\w+\)?:]] 
cant work

**Comment by wuxiao889** [comment]
meet this too
pattern = [[\b(KEYWORDS)\(\w+\)?:]]
cant work

**Comment by wuxiao889** [comment]
meet this too
pattern = [[\b(KEYWORDS)\\(\w+\\)?:]]
cant work

**Comment by fvall** [comment]
Agree it works with the modification proposed by @kamskry . Closing.
