### ISSUE TITLE
feature: Allow multiple highlight colors (expand #255)

### ISSUE THREAD

**Issue by aarondill** [folke/todo-comments.nvim#306]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

I'd like to highlight the user portion of todo comments in a different color.
For example, in the below, `FIXME` would be one color, `(folke)` would be a different, and `: something is broken` would remain unhighlighted.
```lua
--- FIXME(folke): something is broken
```

### Describe the solution you'd like

Accept a list for the `color` argument. Color each capture group in the regex after the first with it's corresponding color.
For example, the below would accomplish the above highlighting.
```lua
{
    keywords = {
      FIXME = {  color = {"error", "user"} }
    },
    colors = {
      error = { fg = "#ff0000" },
      user = { fg = "#ffa500" },
    },
    highlight = {
      pattern = [[.*<((KEYWORDS)\s*(.*)?\s*:)]],
      multiline = false,
      after = "",
      keyword = "bg",
    },
}
```

### Describe alternatives you've considered

1. reverting to the builtin `comment.scm` and `tree-sitter-comment`
2. Leave it as is.

**Comment by aarondill** [comment]
This is similar to the desired result (this is `tree-sitter-comment`):
![2024-08-02_17-34](https://github.com/user-attachments/assets/d89b8b81-4efb-4dde-ad49-3718ab4a3742)

**Comment by Kyren223** [comment]
@aarondill Hey, I am looking for this exact feature, how did u achieve what's in your screenshot?

**Comment by aarondill** [comment]
@Kyren223, that screenshot is currently impossible to replicate with this plugin.
If you want *exactly* that screenshot though, you can uninstall this plugin and install the typescript comment parser via `:TSInstall comment`

**Comment by Kyren223** [comment]
@aarondill ah thx, I might end up forking this, I have wanted to have more customization for a while, like being able to specify both a bg and fg per section per type so I can have have 3 splits or even more for -- |TODO|(kyren)|: |text| (| used to indicate diff sections)

**Comment by aarondill** [comment]
if you do, please open a PR to hopefully upstream those changes to the rest of us 😃

**Comment by aarondill** [comment]
not stale.

**Comment by aarondill** [comment]
@Kyren223 did you get anywhere with that?

**Comment by Kyren223** [comment]
Currently I mostly use IntelliJ + IdeaVim (as I code in java), and for what I do in NeoVim (docs for the Java project) I don't really need this feature, so I haven't needed it.
I might pick it up if my next project will use something like Rust where nvim is good at.

**Comment by aarondill** [comment]
a comment a day keeps the stalebot away 😃
