### ISSUE TITLE
feature: extract both fg and bg instead of only fg

### ISSUE THREAD

**Issue by sineptic** [folke/todo-comments.nvim#307]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

Catppuccin theme do logical thing. It changing both fg and bg. 

I need apply __backgound__ to __backgound__(or maybe both fg and bg), but not __foregound__ to __backgound__, how plugin do.

### Describe the solution you'd like

add config key `extract` with possible values: `fg`, `bg`, `both` and set default to `fg` (for backward capability). If you chose `both` now in highlights before and after accept only empty string or `"normal"`, and keyword only `"normal"`, `"wide"` and empty string

### Describe alternatives you've considered

I don't found any solutions. I think it's solvable only on plugin level.

### Additional context

if you realize it I can use `@comment.*` (like @comment.todo, @comment.warning, ...)

**Comment by nstylo** [comment]
I would love to see this improvement too!

**Comment by sineptic** [comment]
this issue continues be relevant.
