### ISSUE TITLE
Change position of label in telescope

### ISSUE THREAD

**Issue by vuki656** [folke/todo-comments.nvim#31]
Hey, love the plugin.

I have a feature request regarding telescope integration.

Would it be possible to change the position of the type (NOTE, FIX, TODO...) in the file list to the left side. For example in the screenshot below, some files are deeply nested and the kind can only be determined by the little icon on the side.

Ideally, comment type would be on the left so you always know what it is, instead of looking at the icon.

So: [icon] [type] [path]

Maybe even remove the content of the note (text after TODO, FIXME...) since it can be visible in the telescope preview and is cluttering the list.

![image](https://user-images.githubusercontent.com/8104698/120892488-dd535580-c60e-11eb-9f75-7068289efc0a.png)

Thanks for the amazing plugin!

**Comment by folke** [comment]
That makes a lot of sense. I'll change it like you propose.
