### ISSUE TITLE
bug: Doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [folke/todo-comments.nvim#311]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

openSUSE tumbleweed

### Describe the bug

Doesn't work

![image](https://github.com/user-attachments/assets/21da6a35-9fc1-41e4-a69b-13c6b31c3280)

![image](https://github.com/user-attachments/assets/48a6318a-16d6-414b-a50f-dda41244b270)

### Steps To Reproduce

Just try to use

```
local function _1_()
  local todo_comments = require("todo-comments")
  return todo_comments.setup({})
end
return {{"folke/todo-comments.nvim", dependencies = {"nvim-lua/plenary.nvim"}, config = _1_, opts = {signs = true}, lazy = false}}

--TODO

``` 

With the repro.lua:

![image](https://github.com/user-attachments/assets/56eb64f1-8e6d-4662-a1bc-33b80ab9cb47)

### Expected Behavior

To highlight it

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/todo-comments.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by b0ae989c** [comment]
This is not a bug. The default highlight pattern is `.*<(KEYWORDS)\s*:` as described in the docs. So `// TODO` will not be highlighted, but `// TODO: text` will be.

Should close.

**Comment by hrqmonteiro** [comment]
> This is not a bug. The default highlight pattern is `.*<(KEYWORDS)\s*:` as described in the docs. So `// TODO` will not be highlighted, but `// TODO: text` will be.
> 
> Should close.

In case you didn't saw the video, i did that as well

Here it is this pattern in the repro.lua file:

![image](https://github.com/user-attachments/assets/e11607cf-a356-41fd-8426-db8ce55776d5)
![image](https://github.com/user-attachments/assets/6334791e-fc60-4b54-8764-a7108cd5fd0f)

**Comment by b0ae989c** [comment]
There is no video in your post.

Could you make sure `todo-comments.nvim` setup func is actually called? You can check it by running `:Lazy profile`.

If that setup func is not called, you can add `event = 'BufReadPost'` to your config, or call `:lua require('todo-comments').setup()` directly.

**Comment by b0ae989c** [comment]
It is also possible some tasks in the testing framework are blocking the setup func, since it is deferred if it's called during startup. See https://github.com/folke/todo-comments.nvim/blob/8f45f353dc3649cb9b44cecda96827ea88128584/lua/todo-comments/config.lua#L90-L96

For the record, a repro without testing is totally fine. So I suspect this is some async issue in the testing framework.

Repro without testing:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
	"folke/tokyonight.nvim",
	{ "folke/todo-comments.nvim", opts = {} },
	-- TODO: Fix
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
vim.cmd.colorscheme("tokyonight")
```
Screenshot:
![s](https://github.com/user-attachments/assets/08fd6e38-af17-4294-a12d-01ed21310bbd)

**Comment by fhardison** [comment]
Everything is working for me, but not the highlighting. I tried calling ":lua require('todo-comments').setup()", but didn't get any highlighting. is it possible it's an issue with iterm2 my terminal?
