### ISSUE TITLE
bug: Multiline colouring does not start at beginning of new line

### ISSUE THREAD

**Issue by lobneroO** [folke/todo-comments.nvim#317]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

Windows 11

### Describe the bug

The multiline TODO comment colours the comment, but in every line it starts at the same character (i.e. not in the beginning of a new line). This is a problem, if the `TODO:` string is not the first string of a comment:

![image](https://github.com/user-attachments/assets/17ebac3b-df26-4127-988c-0fa01fc7e153)

### Steps To Reproduce

1. Write a comment  
```
// some text TODO: we need a lot more text
// but there is another line with a lot of text
// and even more text in a third line here
```
2. Note that the TODO colouring starts with the TODO and on the same char index in every following line

### Expected Behavior

Either the entire TODO line (and multiline comment) or at least the entire comment + full following lines are coloured

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/todo-comments.nvim", opts = {} },
    -- add any other plugins here
    -- no special setup

  },
})
```

**Comment by JohnnyAmos** [comment]
I have the same problem on MacOS Sequoia. I haven't submitted an issue because I was going to see if I could fix is and submit a PR, but I haven't had time. I'll try to work on it later tonight.

**Comment by JohnnyAmos** [comment]
Well, that didn't happen. Sometime this week, maybe?
