### ISSUE TITLE
Must never exceed max results

### ISSUE THREAD

**Issue by creepinson** [folke/todo-comments.nvim#32]
```
E5108: Error executing lua .../start/telescope.nvim/lua/telescope/pickers/scroller.lua:66: Must never exceed max results: { result = 30, args = { 30 0 31 } }
```

### How I Found This Error

I made a keybind using lua that calls `:TodoTelescope<CR>`. Then I call the keybind and the todo picker shows up with no results, and if I press the up or down arrow it gives me that error.

**Comment by folke** [comment]
I'm not able  to reproduce this. Can you make a basic example?

**Comment by LuisxSullivaN** [comment]
@folke try calling `:TodoTelescope` in a project with no todos or any other keyword, you got no results within telescope and then scroll down with the key arrow, you should see this error displayed.

**Comment by folke** [comment]
Seems to be a Telescope issue: https://github.com/nvim-telescope/telescope.nvim/pull/293#issuecomment-835886488
