### ISSUE TITLE
Todo highlight don't show in zig

### ISSUE THREAD

**Issue by maxxnino** [folke/todo-comments.nvim#35]
Todo don't show highlight in zig, but treesitter said it's TSComments
![image](https://user-images.githubusercontent.com/34153891/121893973-8d386980-cd59-11eb-86eb-ea324d100637.png)

It show in :TodoTelescope
![TodoTelescope](https://user-images.githubusercontent.com/34153891/121894737-70e8fc80-cd5a-11eb-8131-1aefb1da373b.png)

Typescript is working as normal
![image](https://user-images.githubusercontent.com/34153891/121894463-20719f00-cd5a-11eb-8b72-d1d80c8f4fe3.png)

Please help me, I don't know what caused the problem

**Comment by matu3ba** [comment]
The treesitter grammar is far from perfect and has [several known problems](https://github.com/Himujjal/tree-sitter-zig/issues/1). 
Do you have cases, where zig.vim is not sufficient (ie has errors)? If not, consider deactivating it.

**Comment by maxxnino** [comment]
It's good to know that. Thank you, that's a minor problem.

**Comment by folke** [comment]
I just pushed a change that probably fixes this too. Would be great if someone could verify.

**Comment by matu3ba** [comment]
@folke I can not verify that this is fixed. I used `test/behavior/struct.zig` from https://github.com/ziglang/zig. 
![Screenshot_20210705_135507](https://user-images.githubusercontent.com/13089667/124467801-a18be700-dd98-11eb-8778-1641386f3953.png)
