### ISSUE TITLE
Intereference with lewis6991/gitsigns.nvim

### ISSUE THREAD

**Issue by matu3ba** [folke/todo-comments.nvim#36]
Adding NOTE, TODO, FIXME etc hides the green markings that show where parts were added that usually show up with gitsigns.

What is the recommended way to toggle `signs = true, -- show icons in the signs column` as workaround?

**Comment by folke** [comment]
I just pushed a new release where you can configure `sign_priority`. Should be lower than `6` to give precedence to `git-signs`.

You could also set `signcolumn=2` to have two signs at most
