### ISSUE TITLE
[Feature Request] Multi Line Comment Highlight

### ISSUE THREAD

**Issue by B4rc1** [folke/todo-comments.nvim#37]
Hey, awesome plugin, I really like it, but I find myself writing a lot of multi line comments.
Currently, they are highlighted like this:
![image](https://user-images.githubusercontent.com/10383737/122273859-36aa6700-cee2-11eb-901b-ee60d88b8464.png)
This really bothers me and It would be cool to extend the highlighting of comments to the next line, if the Indentation of the first character aligns/matches.

**Comment by Pasqat** [comment]
I was about to request the same feature, any update? Is it possible?

**Comment by foundObjects** [comment]
I came to suggest the same feature, looks like I'm in good company.

**Comment by crazyminecuber** [comment]
I think this would be a nice feature as well.

**Comment by wizard-28** [comment]
Any updates on this?

**Comment by tim-hilt** [comment]
@wizard-28 just wait or implement it yourself. It’s considered bad form to bump a feature-request like that.

**Comment by mrjones2014** [comment]
This can probably be done using Treesitter right? Might take a stab at a PR for this some time this weekend or next week or something.

**Comment by fioncat** [comment]
Same question, now I disabled non-keyword highlight to make multi-line comments look suitable:

![image](https://user-images.githubusercontent.com/34646834/187586662-20f41ccf-22c1-4157-9af4-2d5ae13e987f.png)

My config:

```lua
require("todo-comments").setup {
  signs = true,
  highlight = {
    before = "", -- "fg" or "bg" or empty
    keyword = "bg", -- "fg", "bg", "wide" or empty. (wide is the same as bg, but will also highlight surrounding characters)
    after = "", -- "fg" or "bg" or empty
    comments_only = true, -- uses treesitter to match keywords in comments only
    max_line_len = 400, -- ignore lines longer than this
    exclude = {}, -- list of file types to exclude highlighting
    pattern = [[.*<(KEYWORDS)[^:]*:]],
  },
}
```

**Comment by andy-bell101** [comment]
I've hopefully addressed this in #131

**Comment by Integralist** [comment]
I actually have found this to be a good thing because it forces me to write concisely a 'title' and then all following lines are my extra context. Just my two cents.

**Comment by daephx** [comment]
Cool addition, works great! The only thing I find a bit weird is how each line adds an entry to the sign column, as opposed to just the line containing the relevant `KEYWORD`.

**Comment by B4rc1** [comment]
Works wonderfully, thank you!

**Comment by B4rc1** [comment]
although I have to agree with @daephx, the signcolumn entry for each line of the comment looks a bit odd

**Comment by folke** [comment]
Right, forgot about that. Fixed!
