### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by kevinpita** [folke/todo-comments.nvim#38]
Hi, sorry for the bad title but not sure how to put it.

I'm using OS X 11.4 Big sur with iterm 2 and a patched font
I cannot get the plugin to work, it doesn't highlight and it doesn't show todos in trouble or telescope

Note: When I say todos I mean everything, hack, perf...

<img width="570" alt="imagen" src="https://user-images.githubusercontent.com/69063372/122643297-8cf3f180-d0fe-11eb-841b-0cdf4ae6629e.png">

[I have even created a branch on my config disabling every plugin that's not todo-comments](https://github.com/kevinpita/nvim_config)

I'm using NVIM v0.5.0-dev+7da86f55a

```
 - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
 - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
 - INFO: $TERM_PROGRAM='iTerm.app'
 - INFO: $COLORTERM='truecolor'
  ```

**Comment by folke** [comment]
The default regexes expect a colon after the keyword, as in

`TODO: test`

**Comment by McAuleyPenney** [comment]
@kevinpita It was actually not working for me just now as well. I updated my neovim install and it's functioning fine again

**Comment by kevinpita** [comment]
> The default regexes expect a colon after the keyword, as in
> 
> `TODO: test`

I'm so sorry didn't know it worked like that, thanks! awesome plugin
