### ISSUE TITLE
Scrolling skips line

### ISSUE THREAD

**Issue by JSchrtke** [folke/todo-comments.nvim#39]
Actual behaviour:
When scrolling in the todo view using j/k, every keypress moves the cursor by 2 lines instead of 1.

Expected behaviour:
Scrolling with j/k moves the cursor down/up by a single line.

Windows 10, 20H2, Build 19042.1052
NVIM v0.5.0-dev+1414-g8cdffd42d
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by folke** [comment]
This was actually an issue in Trouble. All solved now!

**Comment by JSchrtke** [comment]
Yup, can confirm, it all works fine now.
Thanks for the quick fix!
