### ISSUE TITLE
Highlights in Telescope preview not correct

### ISSUE THREAD

**Issue by zeitchef** [folke/todo-comments.nvim#40]
Absolutely love this plugin. Thanks!

The only problem I'm having is that the highlights are off in the Telescope preview (see screenshot):

<img width="1440" alt="Screen Shot 2021-06-24 at 14 49 54" src="https://user-images.githubusercontent.com/6670659/123265585-7c2aed80-d4fb-11eb-9a58-b55ddf61616d.png">

Very possible I've overwritten them somehow, but I don't know what they might be. Any ideas?

**Comment by folke** [comment]
Looks good to me. Can you post a screenshot of how they should look like?

**Comment by zeitchef** [comment]
Sorry, perhaps we’re looking at different things. I’m referring to the contents of the preview pane on the right: the comment is unreadable. Not sure if this is a Telescope issue.

**Comment by folke** [comment]
Oh, right, that is to be expected. Not related to todo-comments indeed.

Telescope uses plenary to preview buffers. Only syntax highlighting is enabled. What you're seeing is the default comment color (grey) for your colorscheme where the result line has been greyed with a bg color.

If you want this fixed, then you'd have to see with the colorscheme author.

Closing this.

**Comment by zeitchef** [comment]
To anyone else that might find this annoying - resetting the `TelescopePreviewLine` highlight gave me good results.
