### ISSUE TITLE
Disable for specific filetypes

### ISSUE THREAD

**Issue by akinsho** [folke/todo-comments.nvim#41]
Hi @folke,

Been giving this plugin a try and enjoying it 👍🏾, I just started also testing out https://github.com/kristijanhusak/orgmode.nvim which includes syntax highlighting for org mode files which use todos for its own purposes/has its own syntax. In this case, I'd rather have that plugin handle things how it wants to rather than have this plugin enabled. Is there a way I can disable the plugin for certain filetypes.

**Comment by akinsho** [comment]
Hmm, actually the syntax is slightly different i.e. `TODO` vs `TODO:` which this plugin matches out of the box, I was trying a different pattern. It doesn't quite clash any more, although I still think there are other areas where they might overlap/I'd rather just disable it in that context just so I don't have to wonder if it ever will 😄 .

**Comment by folke** [comment]
I just added an option for this :)

**Comment by akinsho** [comment]
Thank you 🙏🏾
