### ISSUE TITLE
lazy loading not working 

### ISSUE THREAD

**Issue by Vanderscycle** [folke/todo-comments.nvim#42]
Hi @folke 

Sorry to bother you for help. I am unsure why I can't get this plugin to load and I'm confused why as your other plugins works out of the box :/

the error message is that todo-comments isn't loaded. did you run setup()

my config
```lua
        use {
            "folke/todo-comments.nvim",
            requires = "nvim-lua/plenary.nvim",
            config = function()
                require("todo-comments").setup {
                -- your configuration comes here
                -- or leave it empty to use the default settings
                -- refer to the configuration section below
                }
            end
        }
```

I read the previous issues and entered the following command
```lua
:lua print(vim.inspect(require("todo-comments.config")))
```
The output ( I see its not loaded but I don't know why packer doesn't load)
```
{
  _setup = <function 1>,
  colors = <function 2>,
  keywords = {},
  loaded = false,
  ns = 1,
  options = {},
  setup = <function 3>,
  signs = <function 4>
}
```

I am sure the answer is silly, but I legit can't find it :(

Thanks man

**Comment by Vanderscycle** [comment]
I don't know what I did as I moved on and played more with the config but its working now...

Regardless, Telescope + todo-comments = :exploding_head:

**Comment by ngryman** [comment]
Probably related to https://github.com/folke/todo-comments.nvim/issues/209
