### ISSUE TITLE
[Bug] CMake comments are not highlighted

### ISSUE THREAD

**Issue by uyha** [folke/todo-comments.nvim#43]
I just added a `cmake` parser for `nvim-treesitter` recently and I just checked out this plugin but it doesn't seem to highlight comments in cmake files.
![image](https://user-images.githubusercontent.com/8091245/124394967-faf50700-dd01-11eb-8b75-b61189a60bf9.png)

**Comment by folke** [comment]
Does it work after you do `:e` ?

**Comment by uyha** [comment]
No

**Comment by folke** [comment]
Alright, I'll see what's happening here

**Comment by folke** [comment]
I just pushed a fix for this. Thank you for reporting!

**Comment by uyha** [comment]
Thanks for the awesome work.
