### ISSUE TITLE
:TodoTelescope and :TodoTrouble don't respect .gitignore

### ISSUE THREAD

**Issue by vdrg** [folke/todo-comments.nvim#48]
First of all, this plugin is AWESOME! thanks for your work!

I noticed that when using `:TodoTelescope` or `:TodoTrouble` I get results from all files, including the ones specified in `.gitignore`. I couldn't find a way to configure this, but I believe the expected behavior should be to respect .gitignore by default (like the commands provided by telescope).

**Comment by folke** [comment]
Internally, `rg` is being used which uses `gitignore` by default. did you change the default cmd, and args in the config?

**Comment by vdrg** [comment]
Got it, thank you, the problem was that the directory wasn't a git repository (it just had a .gitignore). This seems to be expected `rg` behavior, closing the issue!
