### ISSUE TITLE
Error when deleting a comment treesitter/query.lua:398: invalid end

### ISSUE THREAD

**Issue by kevinpita** [folke/todo-comments.nvim#49]
It's not an important error but it's one.

When I delete with `dd` a todo comment and then hit `u` to undo I get a treesitter lua error on the statusline

`Error executing lua callback: ...-62d67de/share/nvim/runtime/lua/vim/treesitter/query.lua:398: invalid end`

Every plugin on [my config](https://github.com/kevinpita/nvim_config) is up to date and I'm using the latest version of nvim installed through homebrew

This bug sometimes causes the comment not to be highlighted with the plugin and/or not to have every char displayed (some times I get PER within an invisible F

https://user-images.githubusercontent.com/69063372/125168004-db8f2b80-e192-11eb-89de-5a6bc3bb0a39.mov

**Comment by folke** [comment]
I'm not able to reproduce this. I just pushed a new updated that fixed something that might be related.

Would be good if you could check if it works now for you.

**Comment by kevinpita** [comment]
> 
> 
> I'm not able to reproduce this. I just pushed a new updated that fixed something that might be related.
> 
> Would be good if you could check if it works now for you.

Seems to work fine now, thanks!

**Comment by LuisxSullivaN** [comment]
Hey! I have this exact issue right now:( @kevinpita are you able to reproduce it?
