### ISSUE TITLE
Incompatible with phaazon/hop.nvim

### ISSUE THREAD

**Issue by gegoune** [folke/todo-comments.nvim#5]
Hey, nice plugin!

* `romgrk/nvim-treesitter-context`: seems like floating window showing content gets hidden when cursor is on the line matched by `todo-comments.nvim`
* `phaazon/hop.nvim`: when hop displays its extmarks all other highlighting is disabled, but background of `todo-comments.nvim` strings prevails

Looks super great though!

Bonus question - how does it side with comment parser from treesitter? Should it be uninstalled? Can they be used together?

**Comment by levouh** [comment]
I want to say that the problem with `treesitter-context` happens regardless of this plugin; whenever your cursor is over a comment that plugin doesn't work at all in my experience.

**Comment by folke** [comment]
@levouh thanks. I updated the title
