### ISSUE TITLE
Highlighting not working in terminal

### ISSUE THREAD

**Issue by scrouthtv** [folke/todo-comments.nvim#52]
Hey,

it's me again. After updating to 0.5.0, the plugin is working for me.
I only have one issue: todo comments are not highlighted at all in terminal vim:
![image](https://user-images.githubusercontent.com/23227405/126044424-72e47a7b-b1b0-4a04-b12d-60e0619b73df.png)
(top is terminal nvim, bottom is gnvim).

Any idea what's happening here? Thanks in advance.

**Comment by folke** [comment]
You need `termguicolors`. It doesn't support `cterm` colors.

**Comment by scrouthtv** [comment]
That works. Kind of -- enabling `termguicolors` messes up my current color scheme. Is there any chance for implementing `cterm` colors?

**Comment by folke** [comment]
I'm not planning to support cterm colors
