### ISSUE TITLE
Handle highlight groups priority

### ISSUE THREAD

**Issue by DrKGD** [folke/todo-comments.nvim#53]
Hi, first of all thanks for the awesome plugin!
I'd like to have the whole higroup set to background ...  It works pretty fine by itself.
```
highlight = {
  before = "bg",
  keyword = "wide",
  after = "bg",
},
```
![immagine](https://user-images.githubusercontent.com/44092476/126214712-37e7cf9f-1acc-4f0f-a29c-3665988d4f95.png)

I also setup gitsigns as following.
```
...
gitsigns.setup({
  signs = {
    add          = { text = '┃', hl = 'GitSignsAdd'   , numhl='GitSignsAddNr'   , linehl='GitSignsAddLn',  },
    change       = { text = '█', hl = 'GitSignsAdd'	  , numhl='GitSignsChangeNr', linehl='GitSignsChangeLn'},
    delete       = { text = '┃', hl = 'GitSignsDelete', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn'},
    topdelete    = { text = '█', hl = 'GitSignsDelete', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn'},
    changedelete = { text = '█', hl = 'GitSignsChange', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn'},
  },
  linehl = true,
...
}
```

Let's say all the higroups above (GitSignsAdd, Delete, Change) define a guibg color (I also provide an example for the sake of it
`highlight GitSignsAddLn none guibg=#222222"`). gitsigns higlight groups seem to have the better of todocomments ones.
![immagine](https://user-images.githubusercontent.com/44092476/126216290-5c0a7661-54b3-4763-8006-ddafff7a014c.png)

Of course one solution could rearrange the highlight group of todocomments to foreground only (or to disable linehl in gitsigns)
```
highlight = {
  before = "fg",
  keyword = "fg",
  after = "fg",
},
```
![immagine](https://user-images.githubusercontent.com/44092476/126216892-0f805491-378b-45ff-b636-bfb916e72eea.png)

Is there a better way?
Thanks!

**Comment by folke** [comment]
You can use `sign_priority` for this. Please check the [docs](https://github.com/folke/todo-comments.nvim#%EF%B8%8F-configuration)
