### ISSUE TITLE
Question of the Highlight

### ISSUE THREAD

**Issue by Johan-Palacios** [folke/todo-comments.nvim#55]
I change the Highlight of TODO but it not works, can you help me with this
![image](https://user-images.githubusercontent.com/77251405/128051937-abf2cf35-3dfc-4f66-a272-5443b0ba8486.png)

**Comment by folke** [comment]
Just remove the `LspDiagnosticsDefaultInformation` from that table, otherwise that color will be used instead of the manual color.

**Comment by Johan-Palacios** [comment]
I did it, but it not changes ._.
![image](https://user-images.githubusercontent.com/77251405/128392356-fa3681c2-7da0-43c8-b023-14e0484fcf49.png)

**Comment by folke** [comment]
You need to add a colon after TODO to make it work. So:

```lua
-- TODO: this is a test
```

You can update the patterns used for highlighting and searching if you don't want to add a colon.
