### ISSUE TITLE
Changing default color for FIXME

### ISSUE THREAD

**Issue by dunkeln** [folke/todo-comments.nvim#57]
I have successfully changed highlight color for all the other keywords but for the error keywords like FIX,FIXME and BUG , changing the default color doesn't reflect in the buffers. Is there anything I'm missing out on?

**Comment by folke** [comment]
What color scheme do you use? Probably the colorscheme that is ovewrriding the colors

**Comment by dunkeln** [comment]
ohh im sorry, got really caught up in other stuff. I use the aurora colorscheme

**Comment by Thanatermesis** [comment]
Maybe because there's a conf like this ? 

```lua
  FIX = {
    icon = " ", -- icon used for the sign, and in search results
    color = "error", -- can be a hex color, or a named color (see below)
    alt = { "FIXME", "BUG", "FIXIT", "ISSUE" }, -- a set of other keywords that all map to this FIX keywords
    -- signs = false, -- configure signs for some keywords individually
  },
```

**Comment by jaymorelli96** [comment]
@folke  Is there a way to make the config from `todo-comments` override the theme colors?
