### ISSUE TITLE
Plugin does not work and breaks trouble

### ISSUE THREAD

**Issue by mlthlschr** [folke/todo-comments.nvim#58]
Hi,
i just installed your plugin, only to see that it is not working for me/my setup.

- The keywords do not get highlighted (by bg color like on your screenshots), looks like it is not searching them at all
- when i open trouble `:Trouble` it shows me all the problems of my code, except the todos
- when i try to open the todos with `:TodoTrouble`:
    - the trouble window is empty (the problems are not shown anymore)
    - [Trouble] no results
    - this problem persists until i restart nvim

My config for the two plugins is quite simple: 
```
require('trouble').setup{
    height = 6,
}
require('todo-comments').setup{}
```

**Comment by folke** [comment]
Did you add a colon to the comment?

Like:

```lua
-- TODO: this is a test
```

**Comment by mlthlschr** [comment]
> Did you add a colon to the comment?

yes, i did. but now i tried the way you wrote it: `TODO:` (adding the colon), and it "suddenly" works. looks like i was used to simply writing `TODO` :-)

> Also, it doesn't break trouble. When you open trouble to show todos, it changes the default mode for trouble. Specify any other mode for Trouble to see another list.

Thanks, yeah, i see. thought somehow that  everything goes into one view. might have read the manual a bit better :-)

**Comment by mlthlschr** [comment]
Thanks for your help and keep up the good work!
