### ISSUE TITLE
highlight.after error

### ISSUE THREAD

**Issue by the-spanish-guy** [folke/todo-comments.nvim#59]
I set `highlight.after` as `fg` but it does not work as it should, it colors the whole line

`highlight.after: "fg"`
![fg](https://user-images.githubusercontent.com/32144508/128935342-6bde8780-17a9-4e44-bece-9b05213a8b0a.png)

`highligh.after: "bg"`
![bg](https://user-images.githubusercontent.com/32144508/128935418-7e502295-f29a-4e0c-9a46-b2b2df7f1248.png)

`highlight.after: ""`
![empty](https://user-images.githubusercontent.com/32144508/128935499-d8317c86-7830-4d33-82c8-3451ec63fcc6.png)

I would like the result to be the same as the example in README
![](https://user-images.githubusercontent.com/292349/118135272-ad21e980-b3b7-11eb-881c-e45a4a3d6192.png)

**Comment by folke** [comment]
Can you show me your whole config? It seems you also changed the highlight pattern. There's probably an issue with that

**Comment by piersolenski** [comment]
I just started getting this issue too, my config is simply `require("todo-comments").setup {}`.

**Comment by the-spanish-guy** [comment]
> Can you show me your whole config? It seems you also changed the highlight pattern. There's probably an issue with that
I just changed the nvim theme ([rosé pine](https://github.com/rose-pine/neovim)), and changed the highlight colors for the comments

todo-comments config:
```lua
require("todo-comments").setup({
	signs = true,
	keywords = {
		FIX = {
			icon = " ",
			color = "#eb6f92",
			alt = { "FIXME", "BUG", "FIXIT", "ISSUE" },
		},
		TODO = { icon = " ", color = "#ebbcba" },
		HACK = { icon = " ", color = "#31748f" },
		WARN = { icon = " ", color = "#f6c177", alt = { "WARNING", "XXX" } },
		PERF = { icon = " ", color = "#9ccfd8", alt = { "OPTIM", "PERFORMANCE", "OPTIMIZE" } },
		NOTE = { icon = " ", color = "#c4a7e7", alt = { "INFO" } },
	},
	merge_keywords = true,
	highlight = {
		before = "bg",
		keyword = "bg",
		after = "fg",
		pattern = [[.*<(KEYWORDS)\s*:]],
		comments_only = true,
		max_line_len = 400,
		exclude = {},
	},
	search = {
		command = "rg",
		args = {
			"--color=never",
			"--no-heading",
			"--with-filename",
			"--line-number",
			"--column",
		},
		pattern = [[\b(KEYWORDS):]],
	},
})
```

**Comment by the-spanish-guy** [comment]
The bug has been fixed. It wasn't a `todo-comment` error but a theme error ([#4](https://github.com/rose-pine/neovim/pull/4)).
