### ISSUE TITLE
Text not refreshed after Undo. 

### ISSUE THREAD

**Issue by glyh** [folke/todo-comments.nvim#61]
[![asciicast](https://asciinema.org/a/RV5vsxLaAcjwSwU9bss4c4V6W.svg)](https://asciinema.org/a/RV5vsxLaAcjwSwU9bss4c4V6W)

To reproduce: 
```
TODO: TODOSOMETHING
abcabcabc
```
delete the first line via `dd`.
then press `u` to undo. 
Now the TODOs are not painted correctly. Maybe this is related to the mechanism of this plugin?

**Comment by nagy135** [comment]
I m using nvim-treesitter and it had no effect, how could it?? There seems to be issue with repainting on some events ...i "fix" this with toggling fullscreen of my terminal or scrolling down/up where repaint event is triggered.

**Comment by notpeelz** [comment]
> I m using nvim-treesitter and it had no effect, how could it?? 

todo-comments listens for [treesitter highlight updates](https://github.com/folke/todo-comments.nvim/blob/808a2e524b3720804716a99fd900986b9d727d4d/lua/todo-comments/highlight.lua#L247-L260)

**Comment by nagy135** [comment]
i see, so i probably doesnt have it enabled for language i looked at, mb. But it should not be needed ofc

**Comment by OliverChao** [comment]
> i see, so i probably doesnt have it enabled for language i looked at, mb. But it should not be needed ofc because this limits it just to treesitter supported filetypes.

Hi, I have a similar problem. And I'm also using nim-treesitter. 
I  notice that it will be OK when I refresh the buffer, like using `:e!` or switch to another buffer, or just open nvim-tree.
So, It seems that todo-comments, on some conditions, requires some "force" ops on the buf to  refresh highlights.
