### ISSUE TITLE
Feature request: Make TodoTrouble toggle the menu

### ISSUE THREAD

**Issue by Pirols** [folke/todo-comments.nvim#68]
Hi,

I have just added todo-comments to my neovim configuration but noticed that the command `TodoTrouble` opens the trouble menu but it doesn't actually close it if re-executed. I think it (making `TodoTrouble`toggle the menu) would be an easy, yet very significant improvement to this plugin.
Thanks and keep it up!

**Comment by folke** [comment]
That already works. Just do `:TroubleToggle todo` instead of `TodoToggle`
