### ISSUE TITLE
[Bug] Error executing lua callback: Keyboard interrupt

### ISSUE THREAD

**Issue by chriztheanvill** [folke/todo-comments.nvim#73]
Hi.
If I press O to enter a new line, then Ctrl + c, shows me this message.

![image](https://user-images.githubusercontent.com/37992958/138870702-6d31946b-a6a0-4de3-ad49-8835278d1f4e.png)

**Comment by litewarp** [comment]
Just to chime in with some information, I get this as well when ctrl+c'ing on a new line, but with the following details:

![image](https://user-images.githubusercontent.com/1900476/142142699-1ad3e6eb-3864-405c-ba07-1ac1b6ca8405.png)

**Comment by litewarp** [comment]
So I think this is a neovim issue -- see neovim/neovim#16416

Apparently the solution is to use the following workaround:
```
inoremap <C-c> <Esc>
```
