### ISSUE TITLE
Ripgrep pattern for no colon

### ISSUE THREAD

**Issue by axieax** [folke/todo-comments.nvim#80]
Hi, I want to enable the "match without the extra colon" feature from the README. However, since it doesn't seem to have worked since I got the plugin. Could be something to do with Lua or Plenary's string escape of the backslash character? I'm not too sure, since the ripgrep command seems to match properly raw (please see below). 

![image](https://user-images.githubusercontent.com/62098008/146686318-cd3ce1f6-1609-4d12-bc1a-7fc3b3465ec2.png)

I am currently running ArcoLinux with the latest Rg version (13.0.0). I've tried debugging but am not sure how to print inside callback functions for Plenary jobs. The most I've got is confirmation that my pattern successfully overrides the default pattern, and the pattern doesn't work if I surround the Lua string with single quote characters. Would really appreciate your help :))

**Comment by brightpuddle** [comment]
I thought I had the same issue, but then realized I was missing the highlight pattern. In case you're running into the same issue, here's the complete config to match without the colon. The highlight pattern is a vim regex, and handles highlighting independently from the search functionality.

```lua
require("todo-comments").setup({
    highlight = {
        pattern = [[.*<(KEYWORDS)\s*]],
    },
    search = {
        pattern = [[\b(KEYWORDS)\b]],
    },
})
```

**Comment by axieax** [comment]
👀 tysm @brightpuddle it works now!
