### ISSUE TITLE
todo-comments not highlighting keywords

### ISSUE THREAD

**Issue by ninjarogue** [folke/todo-comments.nvim#81]
this plugin isn't highlighting my keywords. When I add a comment with the keyword included, the color of the text will change, but the keyword itself will not highlight. Even with the default configurations, the keyword highlighting feature doesn't work.

I'm using the latest version of iTerm2, Neovim and tmux on a MAC-Mini MacOS Apple M1

Here is my configuration:
https://github.com/ninjarogue/.dotfiles/blob/master/lua/plugins/todo-comments.lua

**Comment by zmingee** [comment]
I was just having a similar issue, in that the keywords weren't being highlighted at all. I was able to fix it by installing the parser for "comments" in treesitter with:
```
:TSInstall comment
```

Afterwards, keywords were highlighted as expected. Maybe it will work for you.

**Comment by reorx** [comment]
This is something that really should be mentioned in the readme document
