### ISSUE TITLE
Packer error: Expected Lua number

### ISSUE THREAD

**Issue by jhossbach** [folke/todo-comments.nvim#85]
Hey there,
since a few days I get an error in `lua/todo-comments/highlight.lua`, line 278 with `Expected Lua Number`.
It might be related to the latest API change for `nvim_buf_clear_namespace` (see https://github.com/neovim/neovim/issues/14090#issuecomment-1004318147).

**Comment by folke** [comment]
Just pushed a fix for this. That line in the code actually never did what was intended, which resulted in the error being shown.

Fixed it now :)

**Comment by jhossbach** [comment]
Happy to help :)
