### ISSUE TITLE
Customization of sign column separately

### ISSUE THREAD

**Issue by levouh** [folke/todo-comments.nvim#9]
As far as I am aware, and apologies if I'm wrong, but you can't set the sign column foreground/background separately from the rest of the groups.

![image](https://user-images.githubusercontent.com/31262046/118202427-2e5c9900-b417-11eb-8582-99d499f47bd1.png)

Note above how the background for the sign column isn't matched which makes sense based on the highlight groups I've defined, but my `Normal` and `SignColumn` have different background colors for both. The current set of highlight groups ended up looking like:

![image](https://user-images.githubusercontent.com/31262046/118202857-01f54c80-b418-11eb-8670-edec5d2d1176.png)

along with a configuration that looks like:

```
signs = true,
keywords = {
    FIX = {
        icon = ' ',
        color = 'error',
        alt = { 'FIXME', 'BUG', 'FIXIT', 'FIX', 'ISSUE' },
    },
    TODO = {
        icon = ' ',
        color = 'info',
    },
    HACK = {
        icon = ' ',
        color = 'warning',
    },
    WARN = {
        icon = ' ',
        color = 'warning',
        alt = { 'WARNING', 'XXX' },
    },
    PERF = {
        icon = ' ',
        color = 'warning',
        alt = { 'OPTIM', 'PERFORMANCE', 'OPTIMIZE' },
    },
    NOTE = {
        icon = ' ',
        color = 'hint',
        alt = { 'INFO', 'HINT' },
    },
},
highlight = {
    before = '',
    keyword = 'wide',
    after = 'fg',
},
colors = {
    error = { 'TodoCommentError' },
    warning = { 'TodoCommentWarning' },
    info = { 'TodoCommentInfo' },
    hint = { 'TodoCommentHint' },
    default = { 'TodoCommentDefault' },
},
pattern = '(KEYWORDS):',
```

**Comment by folke** [comment]
I'll change it so that the signs use the same bg color as the SignColumn. Won't have time till this evening to add this though. Thank you for reporting!

**Comment by folke** [comment]
I just pushed a fix that correctly uses the configured `SignColumn` bg color.

**Comment by levouh** [comment]
![image](https://user-images.githubusercontent.com/31262046/118279430-5cc68c80-b488-11eb-90ff-5a834063f61d.png)
