### ISSUE TITLE
Doesn't seem to work on my M1 Mac.

### ISSUE THREAD

**Issue by jeffschwartz** [folke/todo-comments.nvim#90]
See below.

**Comment by jeffschwartz** [comment]
BTW, only TODO and HACK are working for me on my M1 Mac. Alts don't seem to work either.

**Comment by jeffschwartz** [comment]
Is this project still being maintained? Just asking :)

**Comment by kbilleter** [comment]
Have you changed the settings?  If not, you'll need to follow the keyword with ':'

**Comment by jeffschwartz** [comment]
@kbilleter sorry for the delay in responding. You are correct, I failed to include the trailing ':". Now everything works beautifully. Thank you for this little gem of a plugin.
