### ISSUE TITLE
[ISSUE]: Icons acting weirdly

### ISSUE THREAD

**Issue by ghost** [folke/todo-comments.nvim#91]
**Describe the bug**
Hello 👋, just added this plugin and want to try it out.
- But the icons are acting weirdly?
- why the icon has a bg? 
- Maybe it's a treesitter issue?

![WindowsTerminal_TAkYKtbNeC](https://user-images.githubusercontent.com/78542955/152905863-48021493-f6f8-47cb-8885-c9b707b50e31.png)

**Desktop Info**
OS: Windows
Terminal: Windows terminal
Neovim Version: 0.6.1

(Sorry for bad english, im not too good at it)

**Comment by Johnsiras** [comment]
Just found out that plenary is the one who's causing the issue...

**Comment by Johnsiras** [comment]
when removing the `requires = "nvim-lua/plenary.nvim"` still does the same thing.
How can i fix this?

**Comment by baddri** [comment]
same issue here.

**Desktop Info**
OS: Linux
Terminal: Kitty
Neovim Version: 0.7.0
