### ISSUE TITLE
Invalid buffer id : 38

### ISSUE THREAD

**Issue by diego-rapoport** [folke/todo-comments.nvim#93]
I'm getting this error message whenever I try to compile sync:
packer.nvim: Error running config for todo-comments.nvim: ...start/todo-comments.nvim/lua/todo-comments/highlight.lua:278: Invalid buffer id: 38

Any hints on how to solve it?

I'm using it with LunarVim configs, by the way.

**Comment by diego-rapoport** [comment]
Sorry, I'm closing this because it seemed to be something wrong about my main config.

**Comment by facundoveliz** [comment]
Hi, i have the same problem. Do you remember what was wrong in your config?

**Comment by facundoveliz** [comment]
here are my [dots](https://github.com/facundoveliz/dotfiles/tree/main/.config/nvim), really i don't know what could this problem be, is the only plugin giving me problems right now
![2022-03-11_11-51](https://user-images.githubusercontent.com/68577124/157890896-389e3bdb-03e4-4c6e-a002-a7b797aea775.png)
.

**Comment by diego-rapoport** [comment]
Sorry, I really can't remember why it happened. Took a quick look into your configs and can't tell anything.

**Comment by facundoveliz** [comment]
No problem, thanks for your help

**Comment by diego-rapoport** [comment]
> No problem, thanks for your help

Hey, just to let you know that I had this kind of problem again, but with another id number and in my config was only a matter of adding a `,` inside a setup I was configuring.
This is why is hard to tell you how to solve since you have a very different config than mine.

Sorry I couldn't be more helpful.

**Comment by silentjay** [comment]
I had to seperate the todo-comments config into it's own lua block in nvim.init to get this message to disappear. Strange.
