### ISSUE TITLE
[Question] color on characters only

### ISSUE THREAD

**Issue by dantenoguera** [folke/todo-comments.nvim#95]
Hi, the plugin is awesome, is there a way to only get color on the keyword's characters and not the background? 
Like this: ![scr](https://user-images.githubusercontent.com/48937707/156613276-1fd6249c-11eb-4ba2-bcff-c60b5be75be2.png)

**Comment by elcih17** [comment]
This is probably what you are looking for

```lua
require("todo-comments").setup {
  highlight = {
    before = "",
    keyword = "fg",
    after = ""
  }
}
```

![Screen Shot 2022-09-06 at 0 06 26](https://user-images.githubusercontent.com/17084445/188478261-3665936b-5696-47df-adc8-ce8ca7cc7a30.png)

**Comment by dantenoguera** [comment]
Yes! Thank you!
