### ISSUE TITLE
[Question] How to modify the pattern to match @todo

### ISSUE THREAD

**Issue by caschbre** [folke/todo-comments.nvim#96]
I haven't been successful at updating the pattern to match the style of todos we use in our code. We prefix with the @ sign, all lowercase and no colon. E.g...
```
// @todo this is a todo.
// @note this is a note.
// @issue this is an issue.
```

I'm not exactly sure how to update the pattern config to make it work for those. Removing the colon isn't an issue, but getting the @ sign is where I'm struggling.

**Comment by ranebrown** [comment]
https://github.com/folke/todo-comments.nvim/issues/30

**Comment by n3wborn** [comment]
#30 didn't help for me btw.

But https://github.com/folke/todo-comments.nvim/issues/177#issuecomment-1421300491 did ! 

![image](https://user-images.githubusercontent.com/10246722/230716013-27b7ffd0-d4c5-49a4-9c19-0a9051828f86.png)
