### ISSUE TITLE
Function that return as string the actual numbers

### ISSUE THREAD

**Issue by Mte90** [folke/todo-comments.nvim#98]
Ideally is enough to have a function that print `3 TODO | 1 FIXME` so it can be used on https://github.com/nvim-lualine/lualine.nvim or other statusline

**Comment by SpicyChickenFLY** [comment]
i agree with @Mte90 ,that would be a useful one

> Ideally is enough to have a function that print `3 TODO | 1 FIXME` so it can be used on https://github.com/nvim-lualine/lualine.nvim or other statusline

**Comment by RAprogramm** [comment]
Do you have idea how to realize counter of todo-comments in lualine?

**Comment by bezhermoso** [comment]
Hey, I wrote a plugin that does what you need to add counts in nvim-lualine: https://github.com/bezhermoso/todos-lualine.nvim

In the meantime, I've requested to make this or something similar part of the plugin itself: https://github.com/folke/todo-comments.nvim/issues/259

**Comment by RAprogramm** [comment]
> Hey, I wrote a plugin that does what you need to add counts in nvim-lualine: https://github.com/bezhermoso/todos-lualine.nvim
> 
> In the meantime, I've requested to make this or something similar part of the plugin itself: https://github.com/folke/todo-comments.nvim/issues/259

I'm already realized todo counter in [NEVIRAIDE](https://github.com/RAprogramm/NEVIRAIDE).

**Comment by Mte90** [comment]
The issue is still there.

**Comment by Mte90** [comment]
it is still there...

**Comment by Mte90** [comment]
I am evaluating to change the plugin I am using  jus t because of this action...

**Comment by Mte90** [comment]
sigh
